### ISSUE TITLE
r21 release can not run in redmi k30, run exception info is "/opt/ndk/android-ndk-r21b/build/../prebuilt/linux-aarch64/bin/make: No Such file or directory"

### ISSUE THREAD

**Issue by m4coding** [Lzhiyong/termux-ndk#10]

**Comment by Lzhiyong** [comment]
> _No description provided._

Only supports aarch64 architecture, please make sure your phone is aarch64 architecture

Don't use proot or chroot linux

**Comment by m4coding** [comment]
redmi k30 is aarch64, now i am use in proot linux

what has any way ues this in proot linux ?

**Comment by Lzhiyong** [comment]
> redmi k30 is aarch64, now i am use in proot linux
> 
> what has any way ues this in proot linux ?

You can try to use [TermuxArch](https://github.com/SDRausty/TermuxArch), or proot to add parameters -b /system/:/system/system/

![IMG_20201015_103559](https://user-images.githubusercontent.com/36750502/96070275-73950880-0ed2-11eb-9c95-45d57cbadaec.jpg)

**Comment by m4coding** [comment]
proot to add parameters -b /system/:/system/

Still the same exception

**Comment by Lzhiyong** [comment]
> proot to add parameters -b /system/:/system/
> 
> Still the same exception

Please try to use termuxarch, there is no problem on my phone

![Screenshot_2020-10-15-11-40-36-590_com termux](https://user-images.githubusercontent.com/36750502/96074512-73e5d180-0edb-11eb-80d9-db829f410627.jpg)

**Comment by hnmn** [comment]
Why am i getting when compiling simple program ?
![IMG_20201015_122137](https://user-images.githubusercontent.com/26086203/96087113-fde46900-0ee0-11eb-90cc-1013a59772f1.jpg)

**Comment by Lzhiyong** [comment]
> Why am i getting when compiling simple program ?
> ![IMG_20201015_122137](https://user-images.githubusercontent.com/26086203/96087113-fde46900-0ee0-11eb-90cc-1013a59772f1.jpg)



> Why am i getting when compiling simple program ?
> ![IMG_20201015_122137](https://user-images.githubusercontent.com/26086203/96087113-fde46900-0ee0-11eb-90cc-1013a59772f1.jpg)

Under normal circumstances, it is not recommended to use proot linux, because there may be some problems, unless you recompile ndk to aarch64 version linux, if you want to use ndk under linux, I recommend TermuxArch

**Comment by hnmn** [comment]
> Under normal circumstances, it is not recommended to use proot linux, because there may be some problems, unless you recompile ndk to aarch64 version linux, if you want to use ndk under linux, I recommend TermuxArch

Sorry but didn't mentioned.
i am not running in a proot.
i am in a termux .

**Comment by Lzhiyong** [comment]
> > Under normal circumstances, it is not recommended to use proot linux, because there may be some problems, unless you recompile ndk to aarch64 version linux, if you want to use ndk under linux, I recommend TermuxArch
> 
> Sorry but didn't mentioned.
> i am not running in a proot.
> i am in a termux .

Try to remove DT_FLAGS_1 for clang and clang++ using termux-elf-cleaner

**Comment by Lzhiyong** [comment]
> > Under normal circumstances, it is not recommended to use proot linux, because there may be some problems, unless you recompile ndk to aarch64 version linux, if you want to use ndk under linux, I recommend TermuxArch
> 
> Sorry but didn't mentioned.
> i am not running in a proot.
> i am in a termux .

Try to remove DT_FLAGS_1 for clang and clang++ using termux-elf-cleaner

**Comment by hnmn** [comment]
```bash
┌u0_a81@localhost ~
└> termux-elf-cleaner /data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang
termux-elf-cleaner: Removing version section from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing version section from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing the DT_RUNPATH dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing the DT_GNU_HASH dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing the DT_VERSYM dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing the DT_VERNEEDNUM dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Removing the DT_VERNEEDED dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang'
┌u0_a81@localhost ~
└> termux-elf-cleaner /data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++
termux-elf-cleaner: Removing version section from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing version section from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing the DT_RUNPATH dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing the DT_GNU_HASH dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing the DT_VERSYM dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing the DT_VERNEEDNUM dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Removing the DT_VERNEEDED dynamic section entry from '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in '/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++'

```
gives below error

>
 ```bash
┌u0_a81@localhost ~
└> /data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android26-clang --sysroot=/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/sysroot hello.c -o hello
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang": empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/clang" (new hash type from the future?)
/data/data/com.termux/files/home/android-ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android26-clang: line 7: 10616 Aborted                 `dirname $0`/clang --target=aarch64-linux-android26 "$@"
```

**Comment by Lzhiyong** [comment]
@hnmn What is your Android version? 
I can’t fix this problem yet. Please use google search or quote [termux package issues](https://github.com/termux/termux-packages/issues/2846) for help

**Comment by m4coding** [comment]
![image](https://user-images.githubusercontent.com/13324985/96953017-bda96a00-1522-11eb-81d5-734b11a4f536.png)

Where to get  this arrch64 toolchain  from?   standard  ndk toolchain is x86

**Comment by Lzhiyong** [comment]
@m4coding aarch64 toolchain from ndk-r21, not x86

**Comment by m4coding** [comment]
standard ndk toolchain only has linux-x86_64，not has linux-aarch64

**Comment by Lzhiyong** [comment]
@m4coding aarch64 toolchain from termux-ndk r21

**Comment by m4coding** [comment]
我的 意思是termux-ndk r21是如何编译出linux-aarch64工具链的？标准的ndk只有linux-x86_64

**Comment by Lzhiyong** [comment]
@m4coding 用我编译好的r21去编译 llvm-toolchain，如果最后llvm-toolchain编译成功后，会生成和官方ndk一样的工具链，然后用我们自己编译的llvm替换掉官方ndk里面的llvm就可以了
