### ISSUE TITLE
android-sdk/build-tools/30.0.3/aidl : 这是一个x86_64的binary

### ISSUE THREAD

**Issue by flyingfish120** [Lzhiyong/termux-ndk#102]
在编译termux时，file android-sdk/build-tools/30.0.3/aidl 后结果为x86_64，在box64环境下运行正常，解决方法为将box64作为依赖加入，并把原有的android-sdk/build-tools/30.0.3/aidl重命名为aidl.bin，替换android-sdk/build-tools/30.0.3/aidl为
#!/bin/bash
#
box64 /path/to/android-sdk/build-tools/30.0.3/aidl $*

作者或许装了box64自动化¿

**Comment by Lzhiyong** [comment]
请重新下载release/sdk
build-tools已经更新到32.0.0
platform-tools 33.0.1
