### ISSUE TITLE
 Error "Unsupported class file major version 61" 

### ISSUE THREAD

**Issue by Anonymous2716** [Lzhiyong/termux-ndk#103]
During building apk I get that  Error "Unsupported class file major version 61"  Which could be solved by jdk 11 . but termux uses jdk 17 . and here I see the jdk 11 is no longer maintained. 
Same issue as this one >>> https://stackoverflow.com/questions/70632741/android-studio-error-unsupported-class-file-major-version-61#:~:text=class%20file%20major%20version%2061%20means%20that%20the%20class%20file,you%20are%20trying%20to%20load.

**Comment by tempaccforissue** [comment]
Just set the `--release 11` or `--release 8` option to the `javac` compiler if you are compiling manually.

The error happens because by default the `javac` of JDK 17 compiles to 17 instead of 11/8. You have to manually set the release version to 11 or 8.

**Comment by Anonymous2716** [comment]
Thanks but some of theme are with cradle.

**Comment by tempaccforissue** [comment]
> Thanks but some of theme are with gradle.

Try to set source and target compatibility in `build.gradle` like this:
`
java {
    sourceCompatibility JavaVersion.11
    targetCompatibility JavaVersion.11
}
`

**Comment by Anonymous2716** [comment]
Solved it other ways. Thanks btw
