### ISSUE TITLE
NDK host architecture. None of the following directories

### ISSUE THREAD

**Issue by xdevkroom** [Lzhiyong/termux-ndk#104]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not determine NDK host architecture. None of the following directories exist: /data/data/com.termux/files/home/opt/android-ndk/prebuilt/linux-x86_64

i used the GL3 example but exit code build fail

**Comment by Lzhiyong** [comment]
I don't know how to solve it, please make sure the path of ndk in `local.properties` is correct and your phone is aarch64 architecture.

**Comment by arcans1998** [comment]
To solve the issue, you need to create a symbolic link
``
ln -s /data/data/com.termux/files/home/opt/android-ndk/prebuilt/linux-linux-aarch64  /data/data/com.termux/files/home/opt/android-ndk/prebuilt/linux-x86_64
``

**Comment by mobutcher** [comment]
ndk高版本不兼容低版本吗？
