### ISSUE TITLE
[Question] - Building with Android IDE

### ISSUE THREAD

**Issue by anonimo82** [Lzhiyong/termux-ndk#105]
Hello everyone.
I'm planning to add NDK support to Android IDE
 - https://github.com/itsaky/AndroidIDE
 - https://androidide.com/
Which would then use it through Termux.

I noticed a .zip download available in the releases, but I didn't try to download it yet, as I wonder how will I install it then.
So, what will I need to do to install NDK support in Android IDE?
Please, point me to a guide or something.

Thanks for any help.

**Comment by Lzhiyong** [comment]
First of all you should understand how to use the command line to compile the app, the IDE just wraps the command line calls.

ndk is called by gradle, not manually, we only need to specify its path or specify its version in gradle.build

see [https://github.com/Lzhiyong/termux-ndk/tree/master/build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)

**Comment by anonimo82** [comment]
Uhm, okay.
But generally speaking, what do I need to do in order to have the NDK executable in path?
Note I'm almost new to this, even if I built something with Android Studio (from command line too, but only with gradlew script) and I really don't know how to invoke the NDK compiler or so.
TBH, I'd just need to be able to build Godot generated projects from Android IDE, and I'm not 101% sure I'll need NDK. Please, see here: 
- https://github.com/godotengine/godot-proposals/discussions/4324
- https://github.com/itsaky/AndroidIDE/issues/148

Thanks =)
