### ISSUE TITLE
Where i find aapt2-7.1.0

### ISSUE THREAD

**Issue by Saikatsaha1996** [Lzhiyong/termux-ndk#106]
Can you guide me please ? @Lzhiyong 
Where i can find aapt2-7.1.0-7984345-linux.jar zip file ?

Which zip i should download ?
![Screenshot_2022-05-22-17-25-49-804_com termux](https://user-images.githubusercontent.com/72664192/169694016-455a03d4-67db-4267-8b15-b7e2ae956d07.jpg)

**Comment by Lzhiyong** [comment]
Just need to update the `aapt2-7.1.0-7984345-linux.jar` file

You can use termux's `aapt2` or use the [sdk-tools/build-tools/aapt2](https://github.com/Lzhiyong/sdk-tools/releases) provided by me

```bash

# copy the aapt2-7.1.0-7984345-linux.jar to your directory
cp ./cache/**/aapt2-7.1.0-7984345-linux.jar your_dir

# copy the aapt2 to your directory
cp /path/to/aapt2 your_dir

# update the aapt2-xxx-linux.jar
jar -uvf aapt2-xxx-linux.jar aapt2
```
now copy `your_dir/aapt2-7.1.0-7984345-linux.jar` to `~/.gradle/cache/modules-2/**/`

**Comment by Saikatsaha1996** [comment]
> ```shell
> cd
> ```

Path to my directory mean ?..
Which path ?

**Comment by Saikatsaha1996** [comment]
> > ```shell
> > cd
> > ```
> 
> Path to my directory mean ?.. Which path ?

@Lzhiyong  🤠
Done thank you..
But i am not closing now.. i will close after some time

**Comment by Saikatsaha1996** [comment]
> Just need to update the `aapt2-7.1.0-7984345-linux.jar` file
> 
> You can use termux's `aapt2` or use the [sdk-tools/build-tools/aapt2](https://github.com/Lzhiyong/sdk-tools/releases) provided by me
> 
> ```shell
> # your directory
> cd /path/to/your_dir
> 
> # copy the aapt2-7.1.0-7984345-linux.jar to your directory
> cp ~/.gradle/cache/**/aapt2-7.1.0-7984345-linux.jar your_dir
> 
> # copy the aapt2 to your directory
> cp /path/to/aapt2 your_dir
> 
> # update the aapt2-7.1.0-7984345-linux.jar
> jar -uvf aapt2-7.1.0-7984345-linux.jar aapt2
> ```
> 
> now copy `your_dir/aapt2-7.1.0-7984345-linux.jar` to `~/.gradle/cache/modules-2/**/aapt2-7.1.0-7984345-linux.jar`

@Lzhiyong hello dear 😊 can I ask you something unofficial about some projects ?

**Comment by Lzhiyong** [comment]
> @Lzhiyong hello dear 😊 can I ask you something unofficial about some projects ?

I don't think I can give you more help with other projects, most of the time it's up to you to figure it out

**Comment by Saikatsaha1996** [comment]
I know that why i was asked for help ☺️
By the way thank you for your help 🤠
