### ISSUE TITLE
require ndk-r21b

### ISSUE THREAD

**Issue by ShinnCuTe** [Lzhiyong/termux-ndk#107]
can you help me ndk r21b aarch64?

**Comment by Lzhiyong** [comment]
> can you help me ndk r21b aarch64?

Why do you need ndk-r21?  I think the `r23` is enough.

**Comment by ShinnCuTe** [comment]
> 

no i only need r21b because my source works just fine on r21b

**Comment by Lzhiyong** [comment]
> > 
> 
> no i only need r21b because my source works just fine on r21b

Hmm, but nothing can help you!

**Comment by fish4terrisa-MSDSM** [comment]
you may try box64 in proot(orusing fex-emu in termux repo,although it may be slow).if you use raspi, box64 is a good choice

**Comment by ShinnCuTe** [comment]
i tried converting r21b but it gives cmake error

**Comment by Lzhiyong** [comment]
> i tried converting r21b but it gives cmake error

r23c + cmake ?

Please use the cmake provided by me, at `android-sdk/cmake`

Please upload your log, or if your project is open source, I can try to compile it for you
