### ISSUE TITLE
使用这个来构建项目和正常ide构建有何不同

### ISSUE THREAD

**Issue by Maritako** [Lzhiyong/termux-ndk#109]
使用termux构建、打包项目与aide构建打包有何不同

**Comment by Lzhiyong** [comment]
Termux打包与`Android studio` 打包方式一样，都是用的gradle插件

安卓上的AIDE不是标准的gradle，用的是他们自己的方式来解析`build.gradle`，AIDE不支持`kotlin`，不支持`cmake`，不支持`java8 lambda`，不支持 `build.gradle.kts`等等，因此AIDE只适合于一些简单的Java安卓工程！

**Comment by Lzhiyong** [comment]
> 使用termux构建、打包项目与aide构建打包有何不同

Termux打包与`Android studio` 打包方式一样，都是用的gradle插件

安卓上的AIDE不是标准的gradle，用的是他们自己的方式来解析`build.gradle`，AIDE不支持`kotlin`，不支持`cmake`，不支持`java8 lambda`，不支持 `build.gradle.kts`等等，因此AIDE只适合于一些简单的Java安卓工程！

**Comment by Maritako** [comment]
谢谢你
