### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Maritako** [Lzhiyong/termux-ndk#110]
我使用 aide 构建了一个 androidx 项目，然后我照着bulid-app里面的介绍修改和添加文件，如下图所示。然后我使用 aide 的打包，选择“默认构建器”，打包成功了，运行也没问题。

我也不知道用你的这个成没成功，感觉没区别。

我只想打包用aide构建的项目有没有详细教程😖😖😖

![IMG_20220803_134026](https://user-images.githubusercontent.com/88639583/182533246-22533b4d-1fa7-424f-8412-a49c6f6447e9.jpg)

**Comment by Lzhiyong** [comment]
请上传错误log

如果你不熟悉命令行工作方式，安卓上还有一个app可以满足你的要求[https://github.com/itsaky/AndroidIDE](https://github.com/itsaky/AndroidIDE)，并且支持Jetpack compose，不过 kotlin没有自动补全，语法诊断，错误提示... 以及不支持NDK，目前还没发布稳定版，不过打包是足够了！
