### ISSUE TITLE
Cmake ndk

### ISSUE THREAD

**Issue by ItzZyann** [Lzhiyong/termux-ndk#113]
Ayo, just asking. ik this is not a issue lmao. But i would ask of how to change cmake android ndk to this ndk? cuz if i compile a shared object it uses android ndk r25c instead of r23c. Is there anyway to change the path or ndk?

**Comment by Lzhiyong** [comment]
Add a `local.properties` file to the root of the project as below
```local.properties
# for example
sdk.dir=/data/data/com.termux/files/home/opt/android-sdk
ndk.dir=/data/data/com.termux/files/home/opt/android-ndk-r23c
cmake.dir=/data/data/com.termux/files/home/opt/android-sdk/cmake
```

**Comment by ItzZyann** [comment]
oh okay, thank you so much:D

**Comment by ItzZyann** [comment]
is it require to add opt/ directory or just to put the path of ndk? cuz mine is located at /files/home/android-ndk-r23c

**Comment by Lzhiyong** [comment]
> is it require to add opt/ directory or just to put the path of ndk? cuz mine is located at /files/home/android-ndk-r23c

/data/data/com.termux/files/home/xxxxxx
any directory

**Comment by ItzZyann** [comment]
Oh okay, thank you so much:D

**Comment by githuber-cyber** [comment]
WARNING: linker: ./cmake: unsupported flags DT_FLAGS_1=0x8000001                            CANNOT LINK EXECUTABLE: cannot locate symbol "in6addr_any" referenced by "./cmake"...
page record for 0x7fb1c10010 was not found (block_size=64)
什么原因？手机系统是安卓6
