### ISSUE TITLE
cmake运行不了

### ISSUE THREAD

**Issue by githuber-cyber** [Lzhiyong/termux-ndk#114]
WARNING: linker: ./cmake: unsupported flags DT_FLAGS_1=0x8000001                            CANNOT LINK EXECUTABLE: cannot locate symbol "in6addr_any" referenced by "./cmake"...
page record for 0x7fb1c10010 was not found (block_size=64)
什么原因？手机系统是安卓6

**Comment by Lzhiyong** [comment]
需要Android 9以上

**Comment by githuber-cyber** [comment]
多谢
