### ISSUE TITLE
Some discussions.

### ISSUE THREAD

**Issue by Anonymous2716** [Lzhiyong/termux-ndk#115]
In proot not as slower as you mentioned . in termux I have built openboard in 33 to 37 minutes and in proof it took about 45 to 47 minutes and in average 15 minutes of time saving. And termux has java 17 . for that we will need gradle 7.3 and up to work. Which most of the projects doesn't use yet. In proot it by default uses jdk11 and I have the options to install jdk 8 to jdk 18.  And this tool is awesome. On device builds.and there is a .properties and a XML file in build-tools versions directories I think. Those files are needed in order to gradle to detect build-tool version. Rest of it could be symlinks . nice documentation .

**Comment by Lzhiyong** [comment]
Unless `temux-app` target api level > 28, you need to consider using proot. At present, `termux-packages` repo has many basic packages, I think it is enough to use.

**Comment by Anonymous2716** [comment]
@Lzhiyong think so.
