### ISSUE TITLE
希望可以像SDK一样提供打包脚本。

### ISSUE THREAD

**Issue by yutong-yt** [Lzhiyong/termux-ndk#117]
打包教程太复杂了，能不能像你发布的sdk一样提供脚本？希望代镜像文件，官方网站没有vpn访问不了。

**Comment by Lzhiyong** [comment]
你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在`gradle.properties`直接指定`aapt2` 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与`Android Studio`完全兼容

```gradle.properties
android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2
```

**Comment by Lzhiyong** [comment]
你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在`gradle.properties`直接指定`aapt2` 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与`Android Studio`完全兼容

```gradle.properties
android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2
```

**Comment by Lzhiyong** [comment]
> 打包教程太复杂了，能不能像你发布的sdk一样提供脚本？希望代镜像文件，官方网站没有vpn访问不了。

你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在`gradle.properties`直接指定`aapt2` 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与`Android Studio`完全兼容

```gradle.properties
android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2
```

**Comment by yutong-yt** [comment]
好吧，是我说的有问题。我想要的是打包ndk，也就是编译ndk，你发的sdk有py脚本直接编译sdk，而ndk啥也没有，编译太麻烦，希望可以提供编译脚步，只需要运行脚本就可以直接编译ndk


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117)




 
你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在gradle.properties直接指定aapt2 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与Android Studio完全兼容
 android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2
 
&mdash;

**Comment by Lzhiyong** [comment]
> 好吧，是我说的有问题。我想要的是打包ndk，也就是编译ndk，你发的sdk有py脚本直接编译sdk，而ndk啥也没有，编译太麻烦，希望可以提供编译脚步，只需要运行脚本就可以直接编译ndk
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月3日(周一) 下午2:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117) 你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在gradle.properties直接指定aapt2 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与Android Studio完全兼容 android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个比较麻烦，源码克隆下来就有30多G，不同版本编译，官网提供的 `llvm-android` 编译脚本都有改动，现在ndk版本大更新都会删除很多文件，这个我没法提供统一的补丁，所以现在我把编译教程都删了，Ndk要想编译成功，你首先得把 `linux-x86_64` 编译成功，搞明白整个编译过程，再编译 `AArch64`的版本

**Comment by yutong-yt** [comment]
不知道你以前编译的时候的文件数据有没有保存，我不需要最新版，只需要可以能直接编译文件，可否把你编译成功的那个源码文件发一下？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117)




  
好吧，是我说的有问题。我想要的是打包ndk，也就是编译ndk，你发的sdk有py脚本直接编译sdk，而ndk啥也没有，编译太麻烦，希望可以提供编译脚步，只需要运行脚本就可以直接编译ndk
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年10月3日(周一) 下午2:51 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117) 你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在gradle.properties直接指定aapt2 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与Android Studio完全兼容 android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这个比较麻烦，源码克隆下来就有30多G，不同版本编译，官网提供的 llvm-android 编译脚本都有改动，现在ndk版本大更新都会删除很多文件，这个我没法提供统一的补丁，所以现在我把编译教程都删了，Ndk要想编译成功，你首先得把 linux-x86_64 编译成功，搞明白整个编译过程，再编译 AArch64的版本
 
&mdash;

**Comment by Lzhiyong** [comment]
> 不知道你以前编译的时候的文件数据有没有保存，我不需要最新版，只需要可以能直接编译文件，可否把你编译成功的那个源码文件发一下？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月3日(周一) 下午3:07 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117) 好吧，是我说的有问题。我想要的是打包ndk，也就是编译ndk，你发的sdk有py脚本直接编译sdk，而ndk啥也没有，编译太麻烦，希望可以提供编译脚步，只需要运行脚本就可以直接编译ndk … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年10月3日(周一) 下午2:51 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117) 你说的是打包Apk，还是打包NDK？如果是打包Apk的话可以在gradle.properties直接指定aapt2 路径就可以了，不需要修改Jar包内的aapt2文件，之所以我在教程没有直接指定aapt2，是为了保证项目与Android Studio完全兼容 android.aapt2FromMavenOverride=/path/to/android-sdk/build-tools/xxx/aapt2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 这个比较麻烦，源码克隆下来就有30多G，不同版本编译，官网提供的 llvm-android 编译脚本都有改动，现在ndk版本大更新都会删除很多文件，这个我没法提供统一的补丁，所以现在我把编译教程都删了，Ndk要想编译成功，你首先得把 linux-x86_64 编译成功，搞明白整个编译过程，再编译 AArch64的版本 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个还真没有保存，测试了大致没什么问题，就删除了，我提供的`ndk-r23c` 应该还能用吧，我现在没有足够时间编译最新NDK和SDK，估计得等到r26才能再编译

**Comment by yutong-yt** [comment]
那好吧，希望下次编译的时候可以把源码保存下来。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 希望可以像SDK一样提供打包脚本。 (Issue #117)
