### ISSUE TITLE
About linux-arm64 build

### ISSUE THREAD

**Issue by Saint-Theana** [Lzhiyong/termux-ndk#12]
I tried many things but still can't build ndk for linux-arm64 secussfully,can you build one?that would be grateful.I believed that there must be others need it like me.
note: not android,just linux-arm64,prooted archlinux on android for example.

**Comment by Lzhiyong** [comment]
@Saint-Theana 
Ndk can be used directly in archlinux, no need to compile separately for linux

![Screenshot_2020-11-30-10-05-24-376_com termux](https://user-images.githubusercontent.com/36750502/100562701-6a7fbf80-32f7-11eb-80c6-0ee3acd18924.jpg)

**Comment by Saint-Theana** [comment]
I got those erro.same in termux.
dont know why.
root@localhost /o/a/t/l/p/l/bin# ./clang
CANNOT LINK EXECUTABLE "./clang.real": library "libc++_shared.so" not found

**Comment by Lzhiyong** [comment]
@Saint-Theana You can try to use [TermuxArch](https://github.com/SDRausty/TermuxArch), or proot to add parameters -b /system/:/system/

**Comment by Saint-Theana** [comment]
your release ndk don't work in termux.
It's it due to phone model?or Android version?


$ arch/opt/android-ndk-r21d/toolchains/llvm/prebuilt/linux-aarch64/bin/clang
CANNOT LINK EXECUTABLE "arch/opt/android-ndk-r21d/toolchains/llvm/prebuilt/linux-aarch64/bin/clang.real": library "libc++_shared.so" not found
$
$
$

**Comment by Lzhiyong** [comment]
@Saint-Theana Android OS needs /system/lib/libc++_shared.so or /system/lib64/libc++_shared.so

or copy libc++_shared.so to android-ndk-r21d/toolchains/llvm/prebuilts/linux-aarch64/lib64

**Comment by lateautumn233** [comment]
![Screenshot_2021-02-17-20-01-57-219_com server auditor ssh client](https://user-images.githubusercontent.com/63851402/108201651-17c9dd00-715b-11eb-9812-b472142547a7.jpg)

I'm trying to compile arm64 linux ndk. 
Google Translate
