### ISSUE TITLE
没有那个文件或目录

### ISSUE THREAD

**Issue by keroushe** [Lzhiyong/termux-ndk#120]
使用android-ndk-r23c-aarch64 release包，在Linux aarch64上执行ndk-build命令，出现“make: 没有那个文件或目录”, 请问下是什么原因, 谢谢.

[root@application demo]# /root/hexs/ndk_r23_aarch64/android-ndk-r23c/ndk-build --version
/root/hexs/ndk_r23_aarch64/android-ndk-r23c/build/ndk-build:行218: /root/hexs/ndk_r23_aarch64/android-ndk-r23c/build/../prebuilt/linux-aarch64/bin/make: 没有那个文件或目录

Linux application 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Lzhiyong** [comment]
直接在Termux里构建就可以，使用proot可能会有一些问题，我并没有适配 `linux-aarch64`，二进制如果不是是静态编译的，会不兼容

Termux本来就有`openjdk-17`，没必要使用linux发行版本，而且直接在termux进行编译速度要快一些

**Comment by keroushe** [comment]
嗯，我这边是要用Linux aarch64上使用ndk去编译jni工程
