### ISSUE TITLE
CMAKE ERROR

### ISSUE THREAD

**Issue by sradityaa** [lzhiyong/termux-ndk#122]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1405] error when building with cmake using /data/data/com.termux/files/home/GL3/app/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/cmake with arguments {-H/data/data/com.termux/files/home/GL3/app/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=24 -DANDROID_PLATFORM=android-24 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/data/data/com.termux/files/usr/share/android-sdk/ndk/24.0.8215888 -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/usr/share/android-sdk/ndk/24.0.8215888 -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/usr/share/android-sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/GL3/app/build/intermediates/cxx/RelWithDebInfo/6f73dx6b/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/GL3/app/build/intermediates/cxx/RelWithDebInfo/6f73dx6b/obj/arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -B/data/data/com.termux/files/home/GL3/app/.cxx/RelWithDebInfo/6f73dx6b/arm64-v8a -GNinja -DANDROID_STL=c++_static}
  -- Android: Targeting API '24' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Configuring incomplete, errors occurred!
  See also "/data/data/com.termux/files/home/GL3/app/.cxx/RelWithDebInfo/6f73dx6b/arm64-v8a/CMakeFiles/CMakeOutput.log".

  WARNING: linker: /data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/cmake: unsupported flags DT_FLAGS_1=0x8000001
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error in CMakeLists.txt:
    Running

     '/data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/ninja' '--version'

    failed with:

     WARNING: linker: /data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/ninja: unsupported flags DT_FLAGS_1=0x8000001

    CANNOT LINK EXECUTABLE
    "/data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/ninja":
    cannot locate symbol "posix_spawn_file_actions_init" referenced by
    "/data/data/com.termux/files/usr/share/android-sdk/cmake/3.23.1/bin/ninja"...

    Subprocess aborted

  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by sradityaa** [comment]
If I create a regular app without cmake it works. But if you want to use cmake it displays the above error. What's the solution? Anyone help me, thanks

**Comment by Lzhiyong** [comment]
> If I create a regular app without cmake it works. But if you want to use cmake it displays the above error. What's the solution? Anyone help me, thanks

`posix_spawn_file_actions_init` requires Android 9 or above, please use termux's ninja instead

ln -sf /data/data/com.termux/files/usr/bin/ninja /path/to/android-sdk/cmake/bin/ninja
