### ISSUE TITLE
不能链接sqlite

### ISSUE THREAD

**Issue by githuber-cyber** [lzhiyong/termux-ndk#128]
Failed to load native library:sqlite-3.40.1.0-3ed73baf-4f97-4237-91c3-caed3e5dd63a-libsqlitejdbc.so. osinfo: Linux-Android/aarch64                                      java.lang.UnsatisfiedLinkError: /storage/emulated/0/temp/sqlite-3.40.1.0-3ed73baf-4f97-4237-91c3-caed3e5dd63a-libsqlitejdbc.so: dlopen failed: library "/storage/emulated/0/temp/sqlite-3.40.1.0-3ed73baf-4f97-4237-91c3-caed3e5dd63a-libsqlitejdbc.so" needed or dlopened by "/data/data/com.termux/files/usr/opt/openjdk/lib/server/libjvm.so" is not accessible for the namespace "(default)"

**Comment by githuber-cyber** [comment]
so文件放到openjdk/lib/server，又说libunwindstack.so找不到符号Xzs_Construct

**Comment by Lzhiyong** [comment]
> so文件放到openjdk/lib/server，又说libunwindstack.so找不到符号Xzs_Construct

这个错误来源于openjdk，而不是Ndk，没遇到过类似的问题，所以我也不知道怎么解决
