### ISSUE TITLE
Please Update the instructions 

### ISSUE THREAD

**Issue by Xyrn23** [lzhiyong/termux-ndk#129]
So I want to use this tool to build react-native apps that requires you to have an android sdk if you have time can you give a step by step instruction I can follow?thanks  in advance and have a good one.

**Comment by MatejMagat305** [comment]
Well sorry for propagate my video, bot bellow video is link to script, which you can use to set enviroment and continue to normal tutorial...
[Video](https://m.youtube.com/watch?v=7aUh39w_-2Q)

**Comment by Xyrn23** [comment]
@MatejMagat305 thanks I successfully built an apk using react native the problem is when I try following a 3 month ago tutorial I'm having a hard time following it for the reason of react native is so much depends on external libraries so I decided to learn flutter and I got some error while building apk using android-sdk and android-aarch64-static-tool
![Screenshot_20230221_171757](https://user-images.githubusercontent.com/93040266/220311711-6d93c8f6-4783-4e7e-8bb8-e943e781f332.png)

**Comment by fayaz-modz** [comment]
> @MatejMagat305 thanks I successfully built an apk using react native the problem is when I try following a 3 month ago tutorial I'm having a hard time following it for the reason of react native is so much depends on external libraries so I decided to learn flutter and I got some error while building apk using android-sdk and android-aarch64-static-tool
> 
> edit: but I think this not an android-sdk problem it is flutter itself 😭 ![Screenshot_20230221_171757](https://user-images.githubusercontent.com/93040266/220311711-6d93c8f6-4783-4e7e-8bb8-e943e781f332.png)

I managed to install a full blown flutter on my device and everything works fine, even the plugins. (No NDK though)
