### ISSUE TITLE
Clang Not working properly 

### ISSUE THREAD

**Issue by lateautumn233** [Lzhiyong/termux-ndk#13]
The following error occurred while I was using 
I don't know. Then fix it 
My English is very poor 
![Screenshot_2021-01-10-17-08-41-654_com termux](https://user-images.githubusercontent.com/63851402/104118793-8b134e80-5366-11eb-9da7-9ee0284e02d8.jpg)

**Comment by Lzhiyong** [comment]
我又重新上传了一个，加了lib64/libc++_shared.so ，如果还是不能执行的话，有可能是你的安卓版本不支持tls(thread local storage)

**Comment by lateautumn233** [comment]
> 我又重新上传了一个，加了lib64 / libc ++ _ shared.so，如果还是不能执行的话，有可能是你的安卓版本不支持tls（线程本地存储）

我试试
