### ISSUE TITLE
CMake for ndk r17c

### ISSUE THREAD

**Issue by ItzZyann** [lzhiyong/termux-ndk#130]
Ey, ik this is just random, but on this ndk gnustl not existed anymore, and uh
Can u make a Android ndk r17c with cmake? cuz i used or old ver of ndk r17c and theres no cmake support, i just wanted to have cmake since its so easy to build shared object using cmake on r17c and also that is the last ndk which it have gnustl support. Thanks!
If u also have discord can we talk there?
My discord is ItzZyann#2630

**Comment by Lzhiyong** [comment]
patch the `android-ndk-r17c/build/cmake/android.toolchain.cmake` file, refer to [https://github.com/Lzhiyong/termux-ndk/blob/master/patches/ndk/android.toolchain.cmake.patch](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/ndk/android.toolchain.cmake.patch)
