### ISSUE TITLE
How can I use it in Asahi Linux?

### ISSUE THREAD

**Issue by itsoulos** [lzhiyong/termux-ndk#131]
I have downloaded the latest zip file but how can I use it in asahi linux?
I want to build the android sdk tools 

Best regards

**Comment by lzhiyong** [comment]
> I have downloaded the latest zip file but how can I use it in asahi linux? I want to build the android sdk tools
> 
> Best regards

This requires upstream support for Apple Silicon, please refer to [https://github.com/android/ndk/issues/1299](https://github.com/android/ndk/issues/1299)
