### ISSUE TITLE
Build Telegram app

### ISSUE THREAD

**Issue by diskree** [lzhiyong/termux-ndk#132]
Hi :) I try to build [Telegram for Android](https://github.com/DrKLO/Telegram) project just for fun. It requires NDK v. 21.4.7075529 (r21e) and CMake v. 3.10.2.4988404.

I try to build cmake sources for aarch64, then I install your sdk+ndk try to change `ndkVersion` in `build.gradle` files but it not working. I install your cmake in SDK but Telegram for some reason keeps trying to build the project with version 3.10.2 despite the fact that I changed it in `build.gradle`.

Can you help me build NDK r21e + CMake 3.10
2 (maybe I do wrong) for Termux?

`
C/C++: /home/diskree/Telegram/TMessagesProj/jni/CMakeLists.txt debug|armeabi-v7a : CMake Warning at /home/diskree/android-sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:417 (message):                                      An old version of CMake is being used that cannot automatically detect                                                compiler attributes.  Compiler identification is being bypassed.  Some                                                values may be wrong or missing.  Update to CMake 3.19 or newer to use                                                 CMake's built-in compiler identification.                Call Stack (most recent call first):                         /home/diskree/android-sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)                           /home/diskree/Telegram/TMessagesProj/.cxx/Debug/505b6j2l/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)  /home/diskree/Telegram/TMessagesProj/.cxx/Debug/505b6j2l/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)                                                                                                                       > Task :TMessagesProj:configureCMakeDebug FAILED                                                                      FAILURE: Build failed with an exception.                                                                              * What went wrong:                                         Execution failed for task ':TMessagesProj:configureCMakeDebug'.                                                       > C/C++: /home/diskree/Telegram/TMessagesProj/jni/CMakeLists.txt debug|armeabi-v7a : CMake Error at /home/diskree/Telegram/TMessagesProj/jni/CMakeLists.txt:749 (include):           include could not find load file:                                                                                       AndroidNdkModules                                                                                                                                                          * Try:                                                     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.                                                                                        * Get more help at https://help.gradle.org                                                                            BUILD FAILED in 52s                                        34 actionable tasks: 1 executed, 33 up-to-date
`

**Comment by lzhiyong** [comment]
Try to modify the cmake version of [build.gradle](https://github.com/DrKLO/Telegram/blob/7c62a5da968b3d771a8e404bd20ecaa7414cf746/TMessagesProj/build.gradle#L92)

for example:
````
externalNativeBuild {
            cmake {
                version '3.18.5+'
                arguments '-DANDROID_STL=c++_static', '-DANDROID_PLATFORM=android-16', "-j=16"
            }
        }
````

**Comment by diskree** [comment]
I change it in TMessagesProj/build.gradle + TMessagesProj_App/build.gradle & clear caches. CMake 3.10.2 continues to be used for build

![Screenshot_2023-05-13-09-26-36-76_84d3000e3f4017145260f7618db1d683](https://github.com/lzhiyong/termux-ndk/assets/96978370/30396e78-2aba-45e1-8eb2-e32a5683333e)

**Comment by diskree** [comment]
@lzhiyong is it worth trying to build on native termux? I meam do not use proot.

or could it be a feature of the Telegram project? cmake version 3.10.2 is listed somewhere, possibly in some binary file from the inside. it seems that it is necessary to use version 3.10.2 here :(

**Comment by diskree** [comment]
I was able to advance in this task, opened discussions here:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/680
https://github.com/termux/termux-app/discussions/3402

**Comment by diskree** [comment]
Finally I did it: https://github.com/diskree/Telegram-Termux
@lzhiyong thanks for your work!
