### ISSUE TITLE
Could not determine NDK host architecture.

### ISSUE THREAD

**Issue by kyzsuukii** [lzhiyong/termux-ndk#134]
i got issue like this when try build app

![Screenshot_20230615-124952_Termux.png](https://github.com/lzhiyong/termux-ndk/assets/110718021/7e610b1f-4ea3-46fa-ae29-80cde0b82b06)

![Screenshot_20230615-125104_Termux.png](https://github.com/lzhiyong/termux-ndk/assets/110718021/d7077746-e51f-4c5d-9aa1-9b159b1fff72)

**Comment by lzhiyong** [comment]
The path `/data/data/com.termux/files/usr/opt/androud-ndk-r24/prebuilt/linux-x86_64` is wrong

the correct path should be `/data/data/com.termux/files/usr/opt/androud-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64`

I don't know what caused it, it may be the termux's cmake, try to `pkg uninstall cmake`

**Comment by kyzsuukii** [comment]
> The path `/data/data/com.termux/files/usr/opt/androud-ndk-r24/prebuilt/linux-x86_64` is wrong
> 
> the correct path should be `/data/data/com.termux/files/usr/opt/androud-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64`
> 
> I don't know what caused it, it may be the termux's cmake, try to `pkg uninstall cmake`

![Screenshot_20230616-170412_Termux.png](https://github.com/lzhiyong/termux-ndk/assets/110718021/bb28624b-12a2-4ad8-92cb-5899215d8800)


still got that
