### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by Se-Lyan** [Lzhiyong/termux-ndk#14]
Would it be possible for ARM? (I have armv8l)

**Comment by Lzhiyong** [comment]
yes, you can download the source code to build for ARM

**Comment by Se-Lyan** [comment]
Okay, but how ? I dont found for arm

**Comment by Lzhiyong** [comment]
> Okay, but how ? I dont found for arm

Please compile by youself on PC, because I didn't compile to ARM(32bit), only compiled the aarch64 architecture

**Comment by Tanishq-Banyal** [comment]
> Would it be possible for ARM? (I have armv8l)

armv8 = arm64 = aarch64

**Comment by strikersix23** [comment]
my device is supposed to be armv8 but is locked to armv7 trackphone especially likes to this to promote iphones over android

**Comment by strikersix23** [comment]
You can also use github actions 

They use these configs for the packages repository

https://raw.githubusercontent.com/termux/termux-packages/master/.github/workflows/packages.yml

https://raw.githubusercontent.com/termux/termux-packages/master/.github/workflows/docker_image.yml
