### ISSUE TITLE
NDK Updating Request

### ISSUE THREAD

**Issue by mcagabe19** [lzhiyong/termux-ndk#145]
Hello.

I had come here beacuse of [Lime](https://media.discordapp.net/attachments/1051796867442278471/1164088113694507088/image.png?ex=6541f08a&is=652f7b8a&hm=bdb9f36eeb957f238b7abe589e68ff0761fe350898128860fe426b6ca9aaf070&=) and [Hxcpp](https://github.com/HaxeFoundation/hxcpp/commit/34cc184ac5dc46125a11577330460d3a95599a72) updates. Due these I needed r25 or r26 ndk's for android. Haxe Libraries gets newer and I can get build failures due that and I hope you have enough time update Android NDK for Android.

**Comment by RohitVerma882** [comment]
Same
