### ISSUE TITLE
How can  I compile the NDK for linux asahi?

### ISSUE THREAD

**Issue by itsoulos** [lzhiyong/termux-ndk#146]
Dear all,
how can I compile the ndk and the android sdk for Linux asahi (Fedora )
?
Are there some instructions to follow?

Giannis

**Comment by lzhiyong** [comment]
(https://android.googlesource.com/toolchain/llvm_android/+/master/README.md)[https://android.googlesource.com/toolchain/llvm_android/+/master/README.md]

You need to replace linux-x86 with the linux aarch64 toolchain
