### ISSUE TITLE
Uncertain If This Should Help My Situation

### ISSUE THREAD

**Issue by Markeo220** [lzhiyong/termux-ndk#147]
I merely have a question based on some confusion. I'm programming everything on my Android phone directly in termux without using android studio. I've already successfully generated a working APK on another project written purely in Java thanks to your termux-sdk download and settings. Now, however, I'm wanting to add in some C++/C code in addition to the Java, which is FINALLY forcing me to have an actual working NDK, whereas before it didn't really need to work in order to use it for building the Java code. So I'm having problems getting the NDK set up to work correctly under termux, although the linux-aarch64 version of it does have some of its exectuables runnable in Android (whenever they are dynamically linked), although the statically linked ones fail. But in order for me to also compile and link into it the C++/C files which obviously now use cmake, the NDK needs to apparently now be fully working and set up correctly, otherwise I've been getting all kinds of errors under gradle. And being that your termux-sdk had helped me a lot earlier with my finally getting the Java code to build correctly into a fully working APK file on my same phone, I'm now HOPING that your termux-ndk download here will serve THIS purpose as well. So far, it appears that it might, although the number of files I see in your download is of course much smaller than the size of the full NDK download (I've been intent on using version v23, "23.2.8568313" because it corresponds to the release of Android API 31 [Android 12] which is the very latest that my Android device can run, so I've just been setting this as the version for virtually everything).

I'm sorry for having made this an "Issue" because I just wanted clarification as to whether these files and instructions here will work for this purpose, to help add in the additional capability to compile and link in the C++/C files along with the Java source files within the same build, while of course using the Android Gradle Plugin. So will your termux-ndk here give me all that's needed in order to fully build an APK that contains both Java AND C++/C files while building it on my Android device that's considered as being the host system while it is of course running termux? Is this the purpose of this download and these instructions? If it won't be enough to do this, then I assume that I'll need to do a lot more work in striving to create my own "customized" NDK for this purpose, which is what I'm hoping that you've already created here for us that will work in this regard.  Thank you.  :)

**Comment by zongou** [comment]
Off topic: 
coding with CLI is kinda hard i think.
i have build vscode oss server runs directly on raw android and prooted enviroment with some fixed to work better on android, i think you would be interested. And contribution are wellcome.

https://github.com/lzhiyong/termux-ndk/assets/23202896/b970ec12-3f61-406e-9199-dab01edeb3b8


https://github.com/lzhiyong/termux-ndk/assets/23202896/107b5af3-1c63-4a30-9f3e-48ec4d3ba80d

**Comment by dhuux** [comment]
> Off topic: coding with CLI is kinda hard i think. i have build vscode oss server runs directly on raw android and prooted enviroment with some fixed to work better on android, i think you would be interested. And contribution are wellcome.
> 

how to run it in in termux? extract it and `./code-server-oss`?

**Comment by zongou** [comment]
> > Off topic: coding with CLI is kinda hard i think. i have build vscode oss server runs directly on raw android and prooted enviroment with some fixed to work better on android, i think you would be interested. And contribution are wellcome.
> 
> how to run it in in termux? extract it and `./code-server-oss`?

yes, this is how i run it:
```sh
./vscode-reh-web-android-arm64/bin/code-server-oss --host ::0 --without-connection-token
```
you can get help by:
```sh
./vscode-reh-web-android-arm64/bin/code-server-oss --help
```

**Comment by Markeo220** [comment]
I'm only interested in getting C/C++ code to compile within the ndk environment directly on termux using gradle at the command line, I've already done it with Java which no longer presents a problem for me. But I don't use a computer or proot type environment AT ALL because I lack the additional extra space, and Visual Studio--if it runs directly on termux at all--I'm sure would require a lot of space to install.  I believe termux packages provide all of the needed programs that can actually run on Android, so it's got to just be a matter of getting things set up correctly, and I'm thinking that perhaps Lzhiyong has already done this here. I'm being pulled to other things taking up my time at the same time, though, otherwise my next step is to follow her instructions about "Building an App" with termux-ndx and see if that takes me where I need to be to succeed, with my first trying it on the simple "Hello World" app that "gradlew init" creates for the simplest "C/C++ App" choice.  And if following her instructions for building this simple app will work in termux using Gradle, then it will hopefully get everything working for me for more complex C/C++ Apps written and compiled directly withing termux without proot or anything else other than an environment setup to work with all needed programs that will run correctly on Android, including especially the libraries that it will need to use to access the NDK on Android so the Apps can run correctly of course.  I'm very stubborn about sticking with this plan until I succeed with it.  Thanks though.  :)
