### ISSUE TITLE
Build instructions ?

### ISSUE THREAD

**Issue by ddscentral** [lzhiyong/termux-ndk#153]
Build instructions on how to rebuild the package posted in the Releases section would be very helpful. I see there are some patches in the repo but no documentation on how to use them.

My goal is to have an NDK which would run on an ARM host machine (regular Linux, not Android).

**Comment by mcagabe19** [comment]
I think u look at [llvm toolchain's build instructions](https://android.googlesource.com/toolchain/llvm_android/+/master/README.md) and switch x86_64 binaries with aarch64 ones, I tried to at like 2022 but failed
