### ISSUE TITLE
Cmake version

### ISSUE THREAD

**Issue by sjyjoghkkjj** [lzhiyong/termux-ndk#159]
I want to compile telegram, I did everything as needed, but it says an error that it is impossible to determine the cmake version, what should I do?

**Comment by sjyjoghkkjj** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':TMessagesProj:configureCMakeDebug[arm64-v8a]'.
> [CXX1301] Could not get version from cmake.dir path '/storage/emulated/0/javapk/android-sdk/cmake/bin/cmake'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4m 19s
10 actionable tasks: 9 executed, 1 up-to-date

**Comment by lzhiyong** [comment]
Try to specify the cmake version in `TMessagesProj/build.gradle`

note that the `TMessagesProj` seems to only support ndk-r21

```build.gradle
externalNativeBuild {
    cmake {
        path 'jni/CMakeLists.txt'
    }
}
```
