### ISSUE TITLE
Gradle cache error

### ISSUE THREAD

**Issue by jb-hv03** [Lzhiyong/termux-ndk#16]
Hello, I have a problem with gradle and I don't understand :/
![Screenshot_20210208-130758_Termux](https://user-images.githubusercontent.com/45946996/107217943-3ae3e680-6a0f-11eb-8fa6-d0b8d00061bb.jpg)
It's a screenshot of my error. Can you help me please :)
Thanks in advance !

**Comment by Lzhiyong** [comment]
your build.gradle may be wrong, please execute `gradle build --info` for more information

**Comment by Prototype734** [comment]
Tanks for  your answer ! I have run `gradle build --info` and it's a screen of my results
![Screenshot_20210209-132019_Termux](https://user-images.githubusercontent.com/45946996/107363117-00934b80-6ada-11eb-851d-22e8730097a9.jpg)
But when I create a new project with gradle, without any modifications, I have the same error :/
![Screenshot_20210209-065428_Termux](https://user-images.githubusercontent.com/45946996/107363248-29b3dc00-6ada-11eb-918d-91c7d76a85e0.jpg)

**Comment by Lzhiyong** [comment]
please upload your project, let me try to build

**Comment by Prototype734** [comment]
Ok, this is my project generated with gradle 
[hello.zip](https://github.com/Lzhiyong/termux-ndk/files/5951777/hello.zip)
And my android project is a clone of a simple GitHub repository ( https://github.com/chiuki/android-hello-world )

**Comment by Lzhiyong** [comment]
No error
hello
![hello](https://user-images.githubusercontent.com/36750502/107378148-a8366b00-6b26-11eb-8251-0e507749a990.jpg)

**Comment by Lzhiyong** [comment]
No error
hello
![hello](https://user-images.githubusercontent.com/36750502/107378343-d9af3680-6b26-11eb-9871-733e348c0c05.jpg)
android-hello-world
![android-hello-world](https://user-images.githubusercontent.com/36750502/107378409-ea5fac80-6b26-11eb-9464-3225e39c55f8.jpg)

**Comment by Prototype734** [comment]
Why it's don't work on my phone? I have a Samsung on android 10, I don't understand the error :/
Which gradle version are you using please?

**Comment by 0x300T** [comment]
> Why it's don't work on my phone? I have a Samsung on android 10, I don't understand the error :/
> Which gradle version are you using please?

![Screenshot_2021-02-10-02-08-26-080_com sqisland android hello](https://user-images.githubusercontent.com/78304032/107422260-fe1a0b80-6b44-11eb-8a71-409787cc2f28.jpg)
![Screenshot_2021-02-10-02-09-36-262_com termux](https://user-images.githubusercontent.com/78304032/107422288-08d4a080-6b45-11eb-89f7-bef24b2a022e.jpg)

i used gradle 6.8.2
aapt 4.1.1
build toolversion 30.0.3

and it built

but he has some extra settings in his termux i guess
cause he successfully built termux in termux and i can't
