### ISSUE TITLE
关于ndk26的编译

### ISSUE THREAD

**Issue by BRYNHILDRINTHEDARKNESS** [lzhiyong/termux-ndk#160]
你好大佬，我想问一下编译ndk26，是不是用repo下载ndk26的源码后根据你的patch文件对对应位置进行修改，然后编译就可以？编译环境是Ubuntu

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
大佬能否提供联系方式，详细教学？

**Comment by lzhiyong** [comment]
目标平台Android，你需要替换编译工具链为ndk/llvm，这个就可以直接在Texmux里执行

目标平台linux-aarch64，你需要替换编译工具链为arm交叉编译器，这个就可以通过proot或者chroot在Texmux里执行

我没有提交新的的补丁文件，仓库里的补丁不适用于ndk-r26的编译

llvm编译实际是很简单的，基本不会遇到什么错误，runtimes不需要编译，直接复用ndk的就可以，ndk的打包与测试 你需要下载整个ndk仓库的源码大约30G的源码

没有从零开始的教程！！

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 目标平台Android，你需要替换编译工具链为ndk/llvm，这个就可以直接在Texmux里执行
> 
> 目标平台linux-aarch64，你需要替换编译工具链为arm交叉编译器，这个就可以通过proot或者chroot在Texmux里执行
> 
> 我没有提交新的的补丁文件，仓库里的补丁不适用于ndk-r26的编译
> 
> llvm编译实际是很简单的，基本不会遇到什么错误，runtimes不需要编译，直接复用ndk的就可以，ndk的打包与测试 你需要下载整个ndk仓库的源码大约30G的源码
> 
> 没有从零开始的教程！！

我是在安卓平台，您的意思是不是用termux编译llvm然后将llvm里面的clang clang++ clang17替换到ndk里面就可以

**Comment by lzhiyong** [comment]
你在手机里编译也是可以的，那就是host编译了，编译出来的就是aarch64架构，只是编译速度太慢了

这里不建议直接使用termux的clang进行编译，因为编译出来的二进制文件就会依赖于Termux环境，不能单独使用，可以使用本仓库的ndk进行编译

记住runtimes是不需要重新编译的，这是google预编译好的安卓库，对应的就是ndk下的sysroot下的一些东西，重编译没有意义，而且会有很多错误，我估计你解决不了

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 你在手机里编译也是可以的，那就是host编译了，编译出来的就是aarch64架构，只是编译速度太慢了
> 
> 这里不建议直接使用termux的clang进行编译，因为编译出来的二进制文件就会依赖于Termux环境，不能单独使用，可以使用本仓库的ndk进行编译
> 
> 记住runtimes是不需要重新编译的，这是google预编译好的安卓库，对应的就是ndk下的sysroot下的一些东西，重编译没有意义，而且会有很多错误，我估计你解决不了
> 
> 最后替换我使用的是官方的打包命令，而不是手工替换，这里面还包含了测试命令等，当然你也可以手工替换，我之所以使用官方的打包命令，最主要还是为了测试ndk的正确性

但我有一个地方不理解，用Ubuntu去编译llvm_toolchain这样编译出的架构是Linux-x86_64的，如何修改成安卓可用的aarch64架构呢？还请大佬帮忙解答解答

**Comment by lzhiyong** [comment]
用linux arm交叉编译工具链或者ndk都可以，android-ndk本身就是交叉编译工具链，你在ubuntu下用ndk编译的二进制，动态库是直接可以在安卓上运行的！

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 用linux arm交叉编译工具链或者ndk都可以，android-ndk本身就是交叉编译工具链，你在ubuntu下用ndk编译的二进制，动态库是直接可以在安卓上运行的！
> 
> 如果你不明白什么是交叉编译，先查找资料学习一下

大佬我明白你的意思，交叉编译我懂，不仅仅是Ubuntu里面，win也可以编译动态库在安卓上用，我的意思是我在Ubuntu上面要执行Python toolchain/llvm_android/build.py去编译ndk，但是编译出来的ndk是官方发布的适用于Linux x86_64的架构，我想编译在termux使用的aarch64架构，应该去改源码哪些位置呢

**Comment by lzhiyong** [comment]
toolchain/llvm_android/paths.py 定义了toolchain的路径，修改指向你自己的工具链路径，或者把默认的删掉，把你自己的复制到默认工具链路径下

比如默认工具链是/path/to/clang-r407958
你就把clang-r407958下的bin和lib删掉，把ndk/toolchains/**/bin 和lib64复制到clang-r407958这个目录下面

好久没编译了，我都记不清了，里面要修改的还有好几项，你自行debug吧
目前我自己在做一款游戏，所以没时间编译新的版本

每次编译我也是要花很长的时间进行不断的调试，修改toolchain/llvm_android下的一些文件

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> toolchain/llvm_android/paths.py 定义了toolchain的路径，修改指向你自己的工具链路径，或者把默认的删掉，把你自己的复制到默认工具链路径下
> 
> 比如默认工具链是/path/to/clang-r407958 你就把clang-r407958下的bin和lib删掉，把ndk/toolchains/**/bin 和lib64复制到clang-r407958这个目录下面
> 
> 好久没编译了，我都记不清了，里面要修改的还有好几项，你自行debug吧 目前我自己在做一款游戏，所以没时间编译新的版本
> 
> 每次编译我也是要花很长的时间进行不断的调试，修改toolchain/llvm_android下的一些文件

好的大佬太感谢你了，能否提供一个联系方式，后面不要再这里问了，太麻烦了

**Comment by lzhiyong** [comment]
联系方式就不提供了，并不是怕打扰我，而是我能提供的帮助真的非常有限，只能说是一个大概得思路

事实上，你+搜索引擎可以解决掉90%以上的问题
