### ISSUE TITLE
question

### ISSUE THREAD

**Issue by UltraSina** [lzhiyong/termux-ndk#163]
do you think its possible to use it inside android application?

**Comment by robertkirkman** [comment]
Yes, you can use Termux as a Runtime base library for the Bash language, write your script in Bash, then package an edited Termux.apk file that **auto runs your script** and so auto downloads, or auto extracts the termux-ndk and does whatever you would like. If you need help implementing that type of .apk, you could ask me for tips.

**Comment by robertkirkman** [comment]
So basically, **your app could be a complete copy and paste of the entire Termux app's source code, except for specifically the [bashrc file of the bash package](https://github.com/termux/termux-packages/blob/master/packages/bash/etc-bash.bashrc) which you can insert your custom script into** and you can also insert a prepackaged copy of termux-ndk inside if you like as well. I have done something similar before and it works well.

**Comment by robertkirkman** [comment]
When you create a fork of Termux and compile it, you have two options to choose from, ["generate" bootstrap archives or "build" bootstrap archives](https://github.com/termux/termux-packages/wiki/For-maintainers#generate-bootstrap-archives). People who would like to change the hardcoded path you called "Termux data path" (`/storage/emulated/0/Android/data/com.termux/files/`) to a different location have the option of using the **"build" bootstrap archives** choice to change the `TERMUX_APP_PACKAGE` string to something else without having to have a self-hosted `apt` server. My discord account name is owokitty and my email is tacokoneko@gmail.com, if you are trying to contact me outside of github.
