### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by Melinda996** [lzhiyong/termux-ndk#167]
~ $ ndk-build NDK_PROJECT_PATH=/sdcard/ShowMessages NDK_APPLICATION_MK=/sdcard/ShowMessages/Application.mk APP_BUILD_SCRIPT=/sdcard/ShowMessages/Android.mk       

/data/data/com.termux/files/home/android-ndk-r27b/build/ndk-build: line 181: 31682 Killed                  "$GNUMAKE" -O -f "$PROGDIR/core/build-local.mk" $NDK_ANALYZER_FLAGS "$@"

**Comment by lzhiyong** [comment]
see the issue #166
