### ISSUE TITLE
Unexpected ndk22' Clang Error.

### ISSUE THREAD

**Issue by leonhurricaneX** [Lzhiyong/termux-ndk#17]
I am trying to build Chess Engine "Cfish" written in C.
But newer ndk22' gives unexpected result. During compilation there is no error but the executable is not working.
![Screenshot_20210213-131205~2](https://user-images.githubusercontent.com/77374617/107845581-824ce700-6e02-11eb-863c-4421de877d83.png)
This was not in the previous ndk21b so I switched back to that version again.

😅There is another problem in both Termux's and ndk' clang both gives segmentation fault when compiling some C++ projects for armv7a (32 bit).
![Screenshot_20210212-133112~2](https://user-images.githubusercontent.com/77374617/107845677-60079900-6e03-11eb-8faa-02a76ddeef31.png)

Please can you add GCC-10 toolchains in ndk or even a  guide how to build GCC toolchains for ndk will be really appreciated.🙏

REGARDS.🥰

**Comment by Lzhiyong** [comment]
add `-fno-emulated-tls` cflags or cxxflags for Android TLS
