### ISSUE TITLE
Using older `platforms` files

### ISSUE THREAD

**Issue by WavePlayz** [lzhiyong/termux-ndk#170]
I have the older SDK files, which contain platform files for APIs 30 to 34. Could I copy-paste those in the current SDK's `platforms/` dir? Similarly, can we do this with the build tools as well?

**Comment by lzhiyong** [comment]
no need to cpoy and paste, it will automatically download or you can execute the sdkmanager command to download manually

`/path/to/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/path/to/android-sdk install "platforms;android-30"`
