### ISSUE TITLE
Can be pushed to termux "unstable packages"?

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Lzhiyong/termux-ndk#18]
https://github.com/termux/unstable-packages

**Comment by Lzhiyong** [comment]
> https://github.com/termux/unstable-packages

I think openjdk can be pushed to this repository, ndk and sdk may not
you can @xeffyr to recompile the jdk11

**Comment by xeffyr** [comment]
This doesn't meet our requirements of acceptable package submission.

Brief look on your openjdk-build shows that it must be compiled on-device and thus is not suitable for cross-compiling in our Termux package builder Docker image. If you think that I'm building packages in Termux on device, then know - I don't.

**Comment by Lzhiyong** [comment]
> This doesn't meet our requirements of acceptable package submission.
> 
> Brief look on your openjdk-build shows that it must be compiled on-device and thus is not suitable for cross-compiling in our Termux package builder Docker image. If you think that I'm building packages in Termux on device, then know - I don't.

openjdk-11.0.1 is cross-compiled with android-ndk on PC, not on android device
I think jdk11 can be cross-compiled successfully, but need your x11 libraries
