### ISSUE TITLE
cross compile python3?? 

### ISSUE THREAD

**Issue by 0x300T** [Lzhiyong/termux-ndk#19]
the python3 in android-ndk-r22/toolchains/llvm/prebuilt/linux-aarch64/python3  is prebuilt?? or compiled from source by you??if compiled, how you did with ndk(?having some issues when compiling for android standalone

**Comment by Lzhiyong** [comment]
python3 from termux, `apt download python`, then
extract python_3.9.x_aarch64.deb to llvm-toolchain/prebuilts/python/linux-x86
