### ISSUE TITLE
PATH to rm command

### ISSUE THREAD

**Issue by deckaddict** [Lzhiyong/termux-ndk#2]
Hi,

Great to get a version of the ndk built for arm that can be used inside termux.

I did have a problem though with the paths leading to the rm command not being found properly. I fixed it the following way.

```
android-ndk-r17/build/ndk-build
133c133
< export LD_LIBRARY_PATH=$ANDROID_NDK_ROOT/prebuilt/$HOST_TAG/lib
---
> export LD_LIBRARY_PATH=$ANDROID_NDK_ROOT/prebuilt/$HOST_TAG/lib:$LD_LIBRARY_PATH

```

Do you have any plans to upload the build scripts for this so that things like this can be improved by pull requests or new builds based on newer versions easily can be done?

**Comment by Lzhiyong** [comment]
Sorry, the build script has been deleted. You just need to compile the clang source code with NDK(x86_64), or you can refer to https://github.com/android-ide/aide_ndk.git
If you want to compile all the llvm toolchains, you need to download the Google llvm source code 
repo init https://android.googlesource.com/platform/manifest -b llvm-toolchain
and there is no  error on my mobile phone(CANNOT LINK EXECUTABLE "rm": library "libandroid-support.so" not found)
my device is xiaomi6,rom is AEX

**Comment by Lzhiyong** [comment]
> Hi,
> 
> Great to get a version of the ndk built for arm that can be used inside termux.
> 
> I did have a problem though with the paths leading to the rm command not being found properly. I fixed it the following way.
> 
> ```
> android-ndk-r17/build/ndk-build
> 133c133
> < export LD_LIBRARY_PATH=$ANDROID_NDK_ROOT/prebuilt/$HOST_TAG/lib
> ---
> > export LD_LIBRARY_PATH=$ANDROID_NDK_ROOT/prebuilt/$HOST_TAG/lib:$LD_LIBRARY_PATH
> ```
> 
> Do you have any plans to upload the build scripts for this so that things like this can be improved by pull requests or new builds based on newer versions easily can be done?

Sorry, the build script has been deleted. You just need to compile the clang source code with NDK(x86_64), or you can refer to https://github.com/android-ide/aide_ndk.git
If you want to compile all the llvm toolchains, you need to download the Google llvm source code
repo init https://android.googlesource.com/platform/manifest -b llvm-toolchain
and there is no error on my mobile phone(CANNOT LINK EXECUTABLE "rm": library "libandroid-support.so" not found)
my device is xiaomi6,rom is AEX
