### ISSUE TITLE
这里的sdk是否适用于arm64

### ISSUE THREAD

**Issue by liangjian1994** [Lzhiyong/termux-ndk#21]
我自己用sdkmanager下载的build-tools 30.0.0的aapt与aapt2 都不能使用，根据百度搜索是不支持arm64

**Comment by Lzhiyong** [comment]
构建app请参考[termux-ndk/build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)，不需要自己下载build-tools，因为你自己下载的build-tools都是x86_64的，还需要手工替换里面的二进制为aarch64，我提供了28.0.3   29.0.3   30.0.3，以及gradle插件，你只需要修改build.gardle，具体操作请仔细阅读README

**Comment by liangjian1994** [comment]
谢谢
