### ISSUE TITLE
这个能在Linux deploy上用吗

### ISSUE THREAD

**Issue by XCould** [Lzhiyong/termux-ndk#22]
Linux deploy 安装的debian 我试了但是好像不可以

**Comment by Lzhiyong** [comment]
这个不知道，我基本上都是在原生Termux里使用，你可以尝试[TermuxArch](https://github.com/SDRausty/TermuxArch)，一般是不推荐使用proot linux，因为编译速度相比于原生Termux会慢很多.

**Comment by XCould** [comment]
> 这个不知道，我基本上都是在原生Termux里使用，你可以[尝试TermuxArch](https://github.com/SDRausty/TermuxArch)，一般是不推荐使用proot linux，因为编译速度超过了原生Termux会慢很多。

这个我已经解决了，请问一下我应该怎么创建build-tools 因为我的是30.0.3 或者是更高版本的 直接下载的不可以 这个也是编译的吗 我应该怎么去编译build-tools

**Comment by Lzhiyong** [comment]
编译请参考[sdk-tools](https://github.com/Lzhiyong/sdk-tools)

**Comment by XCould** [comment]
> 编译请参考[sdk-tools](https://github.com/Lzhiyong/sdk-tools)
> build-tools里面的aarch64-linux-android-ld arm-linux-android-ld ...来源于binutils，lld 来源于ndk里面的llvm，llvm-rs-cc bcc-compat 来源于[renderscript](https://github.com/Lzhiyong/termux-ndk/tree/master/renderscript)

好的谢谢
