### ISSUE TITLE
Clang error on build target x86 and x86_64

### ISSUE THREAD

**Issue by rendiix** [Lzhiyong/termux-ndk#23]
i got this err when im trying to cross compile binary target x86 and x86_64, 
for target aarch64 and armeabi compile sucssecfully.
How to solve this?
thanks

![Screenshot_20210407-134436600](https://user-images.githubusercontent.com/16639978/113822535-be1f7f80-97a7-11eb-9cbe-0bc809d2bb17.jpg)

**Comment by Lzhiyong** [comment]
Don't use lld, use binutils ld
Please modify the android-ndk-r22/build/cmake/android.toolchain.cmake file

**Comment by Lzhiyong** [comment]
download the [android.toolchain.cmake](https://github.com/Lzhiyong/test-project/blob/main/android.toolchain.cmake), then copy it to android-ndk-r22/build/cmake

**Comment by rendiix** [comment]
> download the [android.toolchain.cmake](https://github.com/Lzhiyong/test-project/blob/main/android.toolchain.cmake), then copy it to android-ndk-r22/build/cmake

Thank you very much, my problem has been resolved. 
But there is still a little problem, when building static binaries for x86 and x86_64 targets, cmake error .
how to disable eh-frame-hdr for static during linking, and what is the effect if I disable the eh-frame-hdr option?

![Screenshot_20210407-174235959](https://user-images.githubusercontent.com/16639978/113854083-a99faf00-97c8-11eb-948e-62f200eb7dcc.jpg)

**Comment by Lzhiyong** [comment]
static compilation for x86 and x86_64 needs use lld
![IMG_20210417_183100](https://user-images.githubusercontent.com/36750502/115110324-6c4bd600-9fad-11eb-92a9-3679cf4251cc.jpg)
