### ISSUE TITLE
static compilation error, for any architecture

### ISSUE THREAD

**Issue by zaharchenko-test** [Lzhiyong/termux-ndk#24]
everything is fine, but I can't compile the static binaries in any way, which is what I need
![Screenshot_20210416-152732_Termux](https://user-images.githubusercontent.com/74099400/115024089-4993c180-9ec8-11eb-96be-334bf8a308dc.png)

**Comment by zaharchenko-test** [comment]
And another question is how to run ndk-build (android.mk, application.mk) directly in the thermux?

**Comment by zaharchenko-test** [comment]
I'm new to this, just learning, I want you to appreciate my first project, what are the pros and cons, where there are gross mistakes, and maybe give a little advice on how to develop it more reliably

https://github.com/zaharchenko-test/multibox

**Comment by Lzhiyong** [comment]
Please download the [ndk-r21d](https://github.com/Lzhiyong/termux-ndk/releases/download/android-ndk/android-ndk-r21d.tar.xz)，this issue will be fixed in the next version.

**Comment by zaharchenko-test** [comment]
👍
