### ISSUE TITLE
Clang is not working

### ISSUE THREAD

**Issue by stupidestmodder** [Lzhiyong/termux-ndk#25]
so i downloaded the latest release (android-ndk-r22b), and extracted it using "tar -xf android-ndk-r22b.tar.xz", everything worked out and it extracted successfully, i then "cd" to "android-ndk-r22b/toolchains/llvm/prebuilt/linux-aarch64/bin", trying to to run "./aarch64-linux-android30-clang++" outputs "./aarch64-linux-android30-clang++: line 3: ./clang++: No such file or directory", but "clang++" exists in the folder, but also, trying to run "./clang++" outputs "bash: ./clang++: Bad address", i don't know what i could be doing wrong so if you know what i have to do to fix this i would appreciate that.

**Comment by zaharchenko-test** [comment]
android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ app.c
android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target aarch64-linux-android21 app.c 


these both options are completely the same, they work for me ;)

**Comment by zaharchenko-test** [comment]
could you please take a screenshot of the error

**Comment by stupidestmodder** [comment]
also didn't work, here are some screenshots 
![Screenshot_20210416-153057_Termux](https://user-images.githubusercontent.com/44854972/115068958-52d15e00-9ec9-11eb-82e7-c9f3bd6874f2.jpg)
![Screenshot_20210416-153241_Termux](https://user-images.githubusercontent.com/44854972/115068964-549b2180-9ec9-11eb-9c4e-7f3dcf414b2c.jpg)
![Screenshot_20210416-153311_Termux](https://user-images.githubusercontent.com/44854972/115068969-5664e500-9ec9-11eb-86d7-5b08fdb8d0f4.jpg)

**Comment by zaharchenko-test** [comment]
make it simple

run as the current directory "./android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -v",
or
export PATH=$PATH:$HOME/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin

clang++ -v

**Comment by zaharchenko-test** [comment]
the problem was that you did not indicate from where to start clang, I hope my answer will help you

**Comment by zaharchenko-test** [comment]
what is your processor architecture? this ndk is compiled for aarch64

**Comment by stupidestmodder** [comment]
> make it simple
> 
> run as the current directory "./android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -v",
> or
> export PATH=$PATH:$HOME/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin
> 
> clang++ -v

still "Bad address"

thxs for the help anyway

**Comment by stupidestmodder** [comment]
> what is your processor architecture? this ndk is compiled for aarch64

armv8l iirc? It's a Samsung A11

**Comment by zaharchenko-test** [comment]
strange, you definitely downloaded ndk completely without errors?

**Comment by stupidestmodder** [comment]
yeah, i don't know what could be causing this

**Comment by zaharchenko-test** [comment]
from where was the thermux downloaded from?, judging by the last line that is not from the playmarket, your version is running on armhf, what architecture are the packages installed on?

**Comment by stupidestmodder** [comment]
fdroid v0.108

**Comment by zaharchenko-test** [comment]
i can advise you ndk-r15c,


apt install gnupg -y

curl -O https://cctools.info/public.key

apt-key add public.key

echo "deb https://cctools.info termux cctools"> ~ /../ usr / etc / apt / sources.list.d / cctools.list

apt update

 apt install gcc-cctools ndk-sysroot-cctools-api-21-aarch64 -y

echo "export PATH = $ PATH: /data/data/com.termux/files/cctools-toolchain/bin" >> ~ / .bashrc

**Comment by zaharchenko-test** [comment]
aarch64-linux-android-g++ -v

**Comment by zaharchenko-test** [comment]
https://f-droid.org/en/packages/com.termux/

best download from this link

**Comment by mjuned47** [comment]
Confirming that ndk is not working 
When i execute 
./aarch64-linux-android-ar 
It gives no output
Not only that tried aarch64-linux-android-clang++ gives same output
Host : Redmi NOTE 4 (Android 7)

**Comment by zaharchenko-test** [comment]
https://github.com/zaharchenko-test/termux-ndk

this will solve all problems
