### ISSUE TITLE
Getting error no such file or directory

### ISSUE THREAD

**Issue by Saikatsaha1996** [Lzhiyong/termux-ndk#28]
This problem is now sloved

**Comment by Saikatsaha1996** [comment]
This is sloved but now got new erro please help me please guild me
![Screenshot_2021-05-19-15-17-51-809_com termux](https://user-images.githubusercontent.com/72664192/118792681-83842900-b8b5-11eb-9860-bab95f287f36.jpg)

**Comment by Saikatsaha1996** [comment]
Can't find "patches/crypt.h" where is this folder?

**Comment by Lzhiyong** [comment]
> Can't find "patches/crypt.h" where is this folder?

cannot found python3, please download python,
execute the command apt download python, then 
extract python_3.9.x_aarch64.deb to llvm-toolchain/prebuilts/python/linux-x86

[crypt.h](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/crypt.h)

There will be some errors when compiling llvm, please solve it by yourself according to the error prompt！

**Comment by Saikatsaha1996** [comment]
Please guild me actually I am noob...
I am useing termux
Now downloaded
Please tell how to extract please give me command line..

**Comment by Lzhiyong** [comment]
> Please guild me actually I am noob...
> I am useing termux
> Now downloaded
> Please tell how to extract please give me command line..

dpkg -X *.deb /path/to/your_dir

dpkg --help for more infomation

If you encounter an error, please follow the prompts to solve it, or use a search engine, because I can't help you solve all the problems！

**Comment by Saikatsaha1996** [comment]
> > Please guild me actually I am noob...
> > I am useing termux
> > Now downloaded
> > Please tell how to extract please give me command line..
> 
> dpkg -X *.deb /path/to/your_dir
> 
> dpkg --help for more infomation
> 
> If you encounter an error, please follow the prompts to solve it, or use a search engine, because I can't help you solve all the problems！

Ok thank you so much
But when you have one or two minutes free time please try to reply... So it very helpful for me 🥰🥰

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-05-19-18-03-01-745_com termux](https://user-images.githubusercontent.com/72664192/118813232-90604700-b8cc-11eb-9145-ff9ca45beb19.jpg)

Python 3.9 available but same problem

**Comment by Saikatsaha1996** [comment]
Now getting this error 
and cannot find this folder

/data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/sysroot/usr/include.   No such file or directory

that's why I can't paste  "crypt.h"  to  llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/sysroot/usr/include


![Screenshot_2021-05-19-20-35-51-660_com termux](https://user-images.githubusercontent.com/72664192/118836879-ebe8ff80-b8e1-11eb-86dd-42a47ee651d0.jpg)
