### ISSUE TITLE
Help wanted getting error like this every time..

### ISSUE THREAD

**Issue by Saikatsaha1996** [Lzhiyong/termux-ndk#31]
Android version 11
Armv8 aarch64
![Screenshot_2021-05-23-19-34-36-292_com termux](https://user-images.githubusercontent.com/72664192/119264033-282ca080-bbff-11eb-922d-07eca1a6ba09.jpg)

**Comment by Saikatsaha1996** [comment]
/llvm-toolchain/out/llvm-project/llvm
-- The C compiler identification is Clang 12.0.0
-- The CXX compiler identification is Clang 12.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang
-- Check for working C compiler: /data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang - broken
CMake Error at /data/data/com.termux/files/usr/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/data/com.termux/files/home/llvm-toolchain/out/stage1/CMakeFiles/CMakeTmp

    Run Build Command(s):/data/data/com.termux/files/home/llvm-toolchain/prebuilts/build-tools/linux-x86/bin/ninja cmTC_92976 && [1/2] Building C object CMakeFiles/cmTC_92976.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_92976
    FAILED: cmTC_92976
    : && /data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang --sysroot=/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot -ffile-prefix-map=/data/data/com.termux/files/home/llvm-toolchain/= -B/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/bin  -O2 -g -DNDEBUG -B/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -L/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -B/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -L/data/data/com.termux/files/home/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -fuse-ld=lld -Wl,--hash-style=both -L/data/data/com.termux/files/home/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/lib64 -static-libstdc++ CMakeFiles/cmTC_92976.dir/testCCompiler.c.o -o cmTC_92976   && :
    clang-12: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
    ld.lld: error: cannot open crtbegin_dynamic.o: No such file or directory
    ld.lld: error: cannot open crtend_android.o: No such file or directory
    clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/llvm-toolchain/out/stage1/CMakeFiles/CMakeOutput.log".
See also "/data/data/com.termux/files/home/llvm-toolchain/out/stage1/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/do_build.py", line 751, in <module>
    main()
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/do_build.py", line 661, in main
    stage1.build()
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/builder_registry.py", line 67, in wrapper
    function(builder, *args, **kwargs)
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 139, in build
    self._build_config()
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 407, in _build_config
    utils.check_call(cmake_cmd, cwd=self.output_dir, env=env)
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/utils.py", line 56, in check_call
    return subprocess_run(cmd, *args, **kwargs, check=True)
  File "/data/data/com.termux/files/home/llvm-toolchain/toolchain/llvm_android/utils.py", line 46, in subprocess_run
    return subprocess.run(cmd, *args, **kwargs, text=True)
  File "/data/data/com.termux/files/home/llvm-toolchain/prebuilts/python/linux-x86/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,

**Comment by Lzhiyong** [comment]
Don't use clang alone, modify the  toolchains.py `return self.path / 'bin' / 'aarch64-linux-android24-clang'`

no need to use `aarch64-linux-android30-clang`

please refer to [patches](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/toolchains.py.patch)

**Comment by Saikatsaha1996** [comment]
After change I got unknown clang error
![Screenshot_2021-05-24-21-55-16-684_com termux](https://user-images.githubusercontent.com/72664192/119377501-d5281b80-bcda-11eb-8863-bf344dfe03b3.jpg)

**Comment by Saikatsaha1996** [comment]
By mistakely closed

**Comment by Lzhiyong** [comment]
modify the [paths.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/paths.py.patch) and [configs.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/configs.py.patch)

**Comment by Lzhiyong** [comment]
> By mistakely closed

modify the [paths.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/paths.py.patch) and [configs.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/configs.py.patch)

**Comment by Saikatsaha1996** [comment]
Ok ok I will give you updates ... When it complete...

Thank you

**Comment by Saikatsaha1996** [comment]
> > By mistakely closed
> 
> modify the [paths.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/paths.py.patch) and [configs.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/configs.py.patch)

![Screenshot_2021-05-25-10-44-10-808_com termux](https://user-images.githubusercontent.com/72664192/119442904-47821580-bd46-11eb-87f7-b44c89c6f7fb.jpg)

**Comment by Lzhiyong** [comment]
modify llvm-project/compiler-rt/**/CMakeLists.txt
```bash
cd compiler-rt
find . type -name CMakeList.txt | xargs grep latomic 
```
comment out the atomic library

**Comment by Saikatsaha1996** [comment]
# cd llvm-toolchain/toolchain/llvm-project/compiler-rt
# nano CMakeLists.txt

*** Can find atomic library ***
Please mention more some lines 


By the way thank you so much for your support 🙏🙏🙏🙏🥰🥰🥰🥰

![Screenshot_2021-05-25-21-56-37-689_com termux](https://user-images.githubusercontent.com/72664192/119534715-d6be1600-bda4-11eb-880e-a7eeea865907.jpg)
![Screenshot_2021-05-25-21-57-13-456_com termux](https://user-images.githubusercontent.com/72664192/119534722-d887d980-bda4-11eb-932e-583ff28f6fa0.jpg)
![Screenshot_2021-05-25-21-57-37-795_com termux](https://user-images.githubusercontent.com/72664192/119534725-d9207000-bda4-11eb-8b66-1430daa9fedf.jpg)
![Screenshot_2021-05-25-21-57-53-277_com termux](https://user-images.githubusercontent.com/72664192/119534728-d9b90680-bda4-11eb-8a1d-7e46a0ed5507.jpg)
![Screenshot_2021-05-25-21-58-03-345_com termux](https://user-images.githubusercontent.com/72664192/119534731-da519d00-bda4-11eb-8a2f-91df7b7ec37f.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-05-25-22-45-34-210_com termux](https://user-images.githubusercontent.com/72664192/119540314-f22c1f80-bdaa-11eb-8482-fb87db4c6264.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-05-26-00-43-59-307_com termux](https://user-images.githubusercontent.com/72664192/119555485-89996e80-bdbb-11eb-97d8-ca78ed62ec11.jpg)


# NDK r10 requires -latomic almost always
# append_list_if(ANDROID atomic SANITIZER_TEST_LINK_LIBS)
Done but getting error

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-05-26-02-50-19-584_com termux](https://user-images.githubusercontent.com/72664192/119570003-26b0d300-bdcd-11eb-9b41-de9d9de16f9c.jpg)

**Comment by zaharchenko-main** [comment]
https://github.com/zaharchenko-test/termux-ndk/blob/main/README.md

it will solve almost all your mistakes 😉

**Comment by Saikatsaha1996** [comment]
> https://github.com/zaharchenko-test/termux-ndk/blob/main/README.md
> 
> it will solve almost all your mistakes 😉

🤩🤩🤩
