### ISSUE TITLE
need help building NDK-21e for linux arm64

### ISSUE THREAD

**Issue by zaharchenko-test** [Lzhiyong/termux-ndk#32]
could you help build NDK-21e for linux arm64 (not for android), I use Kali nethunter in chroot, it works much faster, I think this release will be useful not only for me

**Comment by Lzhiyong** [comment]
> could you help build NDK-21e for linux arm64 (not for android), I use Kali nethunter in chroot, it works much faster, I think this release will be useful not only for me

The next version will be considered, because I have been busy recently and don’t have enough time to do this!

**Comment by DiskGetor** [comment]
arm64 version released?

**Comment by iHemal** [comment]
> could you help build NDK-21e for linux arm64 (not for android), I use Kali nethunter in chroot, it works much faster, I think this release will be useful not only for me

https://github.com/iHemal/AArch64_NDK

i have built an chroot version of ndk
you can use with nethunter
and it is ndk-r21e lts version

just renderscript is x86 for now
i need to figure out to build for chroot
