### ISSUE TITLE
Got error lpthread

### ISSUE THREAD

**Issue by Saikatsaha1996** [Lzhiyong/termux-ndk#36]
![Screenshot_2021-06-14-22-22-07-096_com termux](https://user-images.githubusercontent.com/72664192/121929679-11412000-cd5f-11eb-9fdc-6f415db167dd.jpg)

**Comment by Lzhiyong** [comment]
Android doesn't implement the pthread_cancel function
please use pthread_kill instead of pthread_cancel
```c
#include <pthread.h>

#define PTHREAD_CANCEL_DISABLE 0
#define PTHREAD_CANCEL_ENABLE 1
#define SIG_CANCEL_SIGNAL SIGUSR1

typedef long pthread_t;

static int pthread_setcancelstate(int state, int *oldstate) {
    sigset_t new, old;
    sigemptyset (&new);
    sigaddset (&new, SIG_CANCEL_SIGNAL);

    int ret = pthread_sigmask(state == PTHREAD_CANCEL_ENABLE ? SIG_BLOCK : SIG_UNBLOCK, &new , &old);
    if(oldstate != NULL) {
        *oldstate =sigismember(&old,SIG_CANCEL_SIGNAL) == 0 ? PTHREAD_CANCEL_DISABLE : PTHREAD_CANCEL_ENABLE;
    }
    return ret;
}

static inline int pthread_cancel(pthread_t thread) {
    return pthread_kill(thread, SIG_CANCEL_SIGNAL);
}
```

**Comment by Saikatsaha1996** [comment]
Ok thank you....
Android not supported lpthread cancel that why I got error 
Can I add this code another place?
![Screenshot_2021-05-20-00-55-16-423_com termux-1](https://user-images.githubusercontent.com/72664192/121993869-dde3ad00-cdc1-11eb-9ab2-68ba3f9b85df.jpg)

**Comment by Saikatsaha1996** [comment]
Can you help me please ?
It's unofficial help..
Help me please..
