### ISSUE TITLE
怎么回事？

### ISSUE THREAD

**Issue by ytxyyt** [Lzhiyong/termux-ndk#38]
报错
![Uploading Screenshot_20210618_151020_com.termux.jpg…]()

**Comment by ytxyyt** [comment]
![Screenshot_20210618_151020_com termux](https://user-images.githubusercontent.com/84581911/122523591-c9194a80-d049-11eb-8edc-a4cf4e1dc894.jpg)

**Comment by Lzhiyong** [comment]
请不要使用proot在linux里面进行操作，直接在Termux里面进行执行就可以了，我并没有编译linux-arm64的版本，后续可能会为linux单独编译ndk和sdk里面的一些工具

**Comment by ytxyyt** [comment]
termux里面可以直接运行gradle？

**Comment by ytxyyt** [comment]
不需要linux

**Comment by ytxyyt** [comment]
？

**Comment by Lzhiyong** [comment]
[build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)
