### ISSUE TITLE
ndk install

### ISSUE THREAD

**Issue by Alexei1981** [Lzhiyong/termux-ndk#4]
Hey.  I did as instructed, but I got the following error.  Can the instructions be more detailed?

```
$ ndk-build
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/data/data/com.termux/files/home/storage/android-ndk-r17/build/core/build-local.mk:146: *** Android NDK: Aborting    .  Stop.
```

**Comment by Lzhiyong** [comment]
cd "your_project_path"
ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk APP_BUILD_SCRIPT=./Android.mk

or

ndk-build NDK_PROJECT_PATH=your_project_path NDK_APPLICATION_MK=your_project_path/Application.mk APP_BUILD_SCRIPT=your_project_path/Android.mk

**Comment by Lzhiyong** [comment]
> Hey. I did as instructed, but I got the following error. Can the instructions be more detailed?
> 
> ```
> $ ndk-build
> Android NDK: Could not find application project directory !
> Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
> /data/data/com.termux/files/home/storage/android-ndk-r17/build/core/build-local.mk:146: *** Android NDK: Aborting    .  Stop.
> ```

cd "your_project_path"
ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk APP_BUILD_SCRIPT=./Android.mk

or

ndk-build NDK_PROJECT_PATH=your_project_path NDK_APPLICATION_MK=your_project_path/Application.mk APP_BUILD_SCRIPT=your_project_path/Android.mk
