### ISSUE TITLE
怎么回事，报错

### ISSUE THREAD

**Issue by ytxyyt** [Lzhiyong/termux-ndk#40]
直接在termux里面运行的

![Screenshot_20210619_022943_com termux](https://user-images.githubusercontent.com/84581911/122603991-d402c800-d0a7-11eb-8a98-294fcb174702.jpg)

**Comment by Lzhiyong** [comment]
这个是警告，并不是真的错误，libjansi.so不影响后面的编译，看下最后有没生成apk包！
