### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by masterjavaofficial** [Lzhiyong/termux-ndk#44]
I've downloaded the openjdk-11.0.1 from your repo's releases section. But it seems not working:

![IMG_20210703_121227](https://user-images.githubusercontent.com/78401450/124345086-6488ee80-dbf8-11eb-9b22-c91c9850fd25.jpg)

Any solution?

**Comment by Lzhiyong** [comment]
Only supports aarch64
What is the architecture of your mobile phone?

**Comment by masterjavaofficial** [comment]
How to know that? Any command in Termux?

**Comment by masterjavaofficial** [comment]
![Screenshot_2021-07-04-10-20-56-468_com termux](https://user-images.githubusercontent.com/78401450/124373151-9a3dde00-dcb1-11eb-9ddb-d1eb64e220e7.jpg)
![Screenshot_2021-07-04-10-17-16-816_com inkwired droidinfo](https://user-images.githubusercontent.com/78401450/124373152-9ca03800-dcb1-11eb-9423-bc2f96fa6668.jpg)

**Comment by Lzhiyong** [comment]
Not support armv7a
