### ISSUE TITLE
Possible to build JDK on Ubuntu?

### ISSUE THREAD

**Issue by itsaky** [Lzhiyong/termux-ndk#46]
Hey,

Is it possible to build the JDK for Android on Ubuntu? Actually, Ubuntu on Termux.

I tried to build the JDK in Ubuntu Terminal (installed in Termux). It was successful. But the problem is, it was built for Linux OS and not for Android.

I know we can perform cross compilation to compile it for Android. But I really don't know how to do it. Could you guide me?

**Comment by Lzhiyong** [comment]
Requires linux-aarch64 version of ndk, you can try to compile the ndk for linux-aarch64, then using the ndk to compile the JDK for Android
actually, it will be more convenient to compile on your computer

**Comment by itsaky** [comment]
The Android Developer website, provides NDK for linux-x86_64 only?

One more thing, if I choose to port the NDK for linux-aarch64, do I need to compile the whole NDK or only the toolchain?

**Comment by itsaky** [comment]
Also, compiling the JDK in Termux emits errors. I managed to fix most of the errors, but I'm stuck with this one:
```
=== Output from failing command(s) repeated here ===
* For target support_native_java.desktop_libjsound_BUILD_LIBJSOUND_link:
ld.lld: error: unable to find library -lasound
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
* For target support_native_jdk.hotspot.agent_libsaproc_BUILD_LIBSA_link:
ld.lld: error: unable to find library -lthread_db
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

* All command lines available in /data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/make-support/failure-logs.
=== End of repeated output ===
```

I had used these commands to configure :
```
./configure \
CC=clang \
CXX=clang++ \
--with-x \
--with-alsa=$HOME/alsa \
--disable-warnings-as-errors \
--with-toolchain-type="clang" \
--with-sysroot=/data/data/com.termux/files \
--with-debug-level=release \
--with-extra-cflags="-fPIC -fno-emulated-tls" \
--with-extra-cxxflags="-fPIC -fno-emulated-tls -std=c++11" \
--with-extra-ldflags="-fuse-ld=lld"
```

And then :
```
make jdk-image
```

I don't know what's wrong with this. I checked if I'm missing any required packages or not. But I can't find anything...

**Comment by itsaky** [comment]
Okay. I managed to fix the issue. But now another in I'm facing another issue :

```
/data/data/com.termux/files/usr/bin/bash: line 5:  5801 Segmentation fault      /data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/support/interim-image/bin/java -XX:DumpLoadedClassList=/data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/support/link_opt/classlist.raw -Djava.lang.invoke.MethodHandle.TRACE_RESOLVE=true -cp /data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/support/classlist.jar build.tools.classlist.HelloClasslist > /dev/null 2>&1 > /data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/support/link_opt/default_jli_trace.txt
make[3]: *** [GenerateLinkOptData.gmk:64: /data/data/com.termux/files/home/jdk/build/linux-aarch64-normal-server-release/support/link_opt/classlist] Error 139
make[2]: *** [make/Main.gmk:512: generate-link-opt-data] Error 2

ERROR: Build failed for target 'jdk-image' in configuration 'linux-aarch64-normal-server-release' (exit code 2)
```

As written in the README, I did :
```
cd build/linux-aarch64-normal-server-release/jdk/lib
termux-elf-cleaner *.so
```

And the I executed ```make jdk-image``` again. But still it prints the same error.

I also tried termux-elf-cleaner in ```build/linux-aarch64-normal-server-release/support/interim-image/lib/*.so```.

But still the same issue...

**Comment by itsaky** [comment]
Built successfully...
