### ISSUE TITLE
编译openjdk12失败

### ISSUE THREAD

**Issue by lateautumn233** [Lzhiyong/termux-ndk#47]
编译openjdk12失败
设备:android11
![Screenshot_2021-07-18-23-08-03-632_com termux](https://user-images.githubusercontent.com/63851402/126072306-1fba597c-dfe6-437d-9f73-6980e1838599.jpg)
![Screenshot_2021-07-18-23-06-09-551_com termux](https://user-images.githubusercontent.com/63851402/126072309-4fcfc482-4fa6-4381-960e-93cf65a7106d.jpg)

如图初步判断jdk11嗝屁了
我没有安卓10设备

**Comment by lateautumn233** [comment]
我在搜索到了这些，根本问题可能是内核更改
https://security.googleblog.com/2019/08/adopting-arm-memory-tagging-extension.html?m=1
https://source.android.com/devices/tech/debug/tagged-pointers

**Comment by lateautumn233** [comment]
我搜索到了https://source.android.com/devices/tech/debug/tagged-pointers
https://security.googleblog.com/2019/08/adopting-arm-memory-tagging-extension.html?m=1
这些应该是相关的

**Comment by Lzhiyong** [comment]
Android 11上关闭tagged pointer，我这里有个库[libmallopt_hook.so](https://github.com/Lzhiyong/termux-ndk/releases/download/openjdk/libmallopt_hook.so) 因为我没有刷Android 11的系统，所以不知道有没有用，你能帮我测试下吗，如果有用的话就把源码发布到release里！

如何使用:
* copy这个库到termux下的任意目录
* 设置LD_PRELOAD环境变量
export LD_PRELOAD=$LD_PRELOAD:/path/to/libmallopt_hook.so

* 恢复的话就把LD_PRELOAD设置回原来的就可以
export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by lateautumn233** [comment]
> 关于Android 11上关闭tagged pointer功能，我这里有个库[libmallopt_hook.so](https://github.com/Lzhiyong/termux-ndk/releases/download/openjdk/libmallopt_hook.so) 因为我没有刷Android 11的系统，所以不知道有没有用，你能帮我测试下吗，如果可行的话，我就把源码发布到release里！
> 
> 如何使用:
> 
> * copy这个库到termux下的任意目录
> * 设置LD_PRELOAD环境变量
>   export LD_PRELOAD=$LD_PRELOAD:/path/to/libmallopt_hook.so
> * 恢复的话就把LD_PRELOAD设置回原来的就可以
>   export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

![Screenshot_2021-07-19-17-10-27-180_com termux](https://user-images.githubusercontent.com/63851402/126134986-db5393b0-b70f-42a5-b92d-e228499ca797.jpg)
并没有作用

**Comment by Lzhiyong** [comment]
因为在Android源码 `core/jni/AndroidRuntime.cpp`下提供了关闭标记指针的方法，不知为何没起作用，你可以自行调试下源码，其实非常的简单，就是利用`LD_PRELOAD`环境变量进行`hook`，加载我们自己`android_mallopt`，而不是调用系统的`android_mallopt`

** 这是源码 **

mallopt_hook.c
```cpp
#include <stdio.h>
#include <errno.h>
#include <android/api-level.h>
#include <sys/system_properties.h>

#include "bionic_malloc.h"


// core/jni/AndroidRuntime.cpp
/*
static void com_android_internal_os_RuntimeInit_nativeDisableHeapPointerTagging(JNIEnv* env, jobject clazz) {
    HeapTaggingLevel tag_level = M_HEAP_TAGGING_LEVEL_NONE;
    if (!android_mallopt(M_SET_HEAP_TAGGING_LEVEL, &tag_level, sizeof(tag_level))) {
        ALOGE("ERROR: could not disable heap pointer tagging\n");
    }
}
*/

static int get_api_level(void) {
    char sdk_ver[PROP_VALUE_MAX];
    if (__system_property_get("ro.build.version.sdk", sdk_ver)) {
        return atoi(sdk_ver);
    }

    return __ANDROID_API__;
}

// hook android_mallopt function
// disable heap pointer tagging
void __attribute__((constructor)) mallopt_hook(void) {
    if(get_api_level() >= 30) {
        HeapTaggingLevel tag_level = M_HEAP_TAGGING_LEVEL_NONE;
        if(!android_mallopt(M_SET_HEAP_TAGGING_LEVEL, &tag_level, sizeof(tag_level))) {
            printf("ERROR: could not disable heap pointer tagging, %s\n", strerror(errno));
        }
    }
}
```

bionic_malloc.h
```cpp
#pragma once

#include <stdbool.h>
#include <stdint.h>

// Structures for android_mallopt.

typedef struct {
  // Pointer to the buffer allocated by a call to M_GET_MALLOC_LEAK_INFO.
  uint8_t* buffer;
  // The size of the "info" buffer.
  size_t overall_size;
  // The size of a single entry.
  size_t info_size;
  // The sum of all allocations that have been tracked. Does not include
  // any heap overhead.
  size_t total_memory;
  // The maximum number of backtrace entries.
  size_t backtrace_size;
} android_mallopt_leak_info_t;

// Opcodes for android_mallopt.

enum {
  // Marks the calling process as a profileable zygote child, possibly
  // initializing profiling infrastructure.
  M_INIT_ZYGOTE_CHILD_PROFILING = 1,
#define M_INIT_ZYGOTE_CHILD_PROFILING M_INIT_ZYGOTE_CHILD_PROFILING
  M_RESET_HOOKS = 2,
#define M_RESET_HOOKS M_RESET_HOOKS
  // Set an upper bound on the total size in bytes of all allocations made
  // using the memory allocation APIs.
  //   arg = size_t*
  //   arg_size = sizeof(size_t)
  M_SET_ALLOCATION_LIMIT_BYTES = 3,
#define M_SET_ALLOCATION_LIMIT_BYTES M_SET_ALLOCATION_LIMIT_BYTES
  // Called after the zygote forks to indicate this is a child.
  M_SET_ZYGOTE_CHILD = 4,
#define M_SET_ZYGOTE_CHILD M_SET_ZYGOTE_CHILD

  // Options to dump backtraces of allocations. These options only
  // work when malloc debug has been enabled.

  // Writes the backtrace information of all current allocations to a file.
  // NOTE: arg_size has to be sizeof(FILE*) because FILE is an opaque type.
  //   arg = FILE*
  //   arg_size = sizeof(FILE*)
  M_WRITE_MALLOC_LEAK_INFO_TO_FILE = 5,
#define M_WRITE_MALLOC_LEAK_INFO_TO_FILE M_WRITE_MALLOC_LEAK_INFO_TO_FILE
  // Get information about the backtraces of all
  //   arg = android_mallopt_leak_info_t*
  //   arg_size = sizeof(android_mallopt_leak_info_t)
  M_GET_MALLOC_LEAK_INFO = 6,
#define M_GET_MALLOC_LEAK_INFO M_GET_MALLOC_LEAK_INFO
  // Free the memory allocated and returned by M_GET_MALLOC_LEAK_INFO.
  //   arg = android_mallopt_leak_info_t*
  //   arg_size = sizeof(android_mallopt_leak_info_t)
  M_FREE_MALLOC_LEAK_INFO = 7,
#define M_FREE_MALLOC_LEAK_INFO M_FREE_MALLOC_LEAK_INFO
  // Change the heap tagging state. The program must be single threaded at the point when the
  // android_mallopt function is called.
  //   arg = HeapTaggingLevel*
  //   arg_size = sizeof(HeapTaggingLevel)
  M_SET_HEAP_TAGGING_LEVEL = 8,
#define M_SET_HEAP_TAGGING_LEVEL M_SET_HEAP_TAGGING_LEVEL
  // Query whether the current process is considered to be profileable by the
  // Android platform. Result is assigned to the arg pointer's destination.
  //   arg = bool*
  //   arg_size = sizeof(bool)
  M_GET_PROCESS_PROFILEABLE = 9,
#define M_GET_PROCESS_PROFILEABLE M_GET_PROCESS_PROFILEABLE
  // Maybe enable GWP-ASan. Set *arg to force GWP-ASan to be turned on,
  // otherwise this mallopt() will internally decide whether to sample the
  // process. The program must be single threaded at the point when the
  // android_mallopt function is called.
  //   arg = bool*
  //   arg_size = sizeof(bool)
  M_INITIALIZE_GWP_ASAN = 10,
#define M_INITIALIZE_GWP_ASAN M_INITIALIZE_GWP_ASAN
  // Disable heap initialization across the whole process. If the hardware supports memory
  // tagging, it also disables memory tagging. May be called at any time including
  // when multiple threads are running. arg and arg_size are unused and must be set to 0.
  // Note that the memory mitigations are only implemented in scudo and therefore this API call will
  // have no effect when using another allocator.
  M_DISABLE_MEMORY_MITIGATIONS = 11,
#define M_DISABLE_MEMORY_MITIGATIONS M_DISABLE_MEMORY_MITIGATIONS
};

typedef enum HeapTaggingLevel {
  // Disable heap tagging. The program must use prctl(PR_SET_TAGGED_ADDR_CTRL) to disable memory tag
  // checks before disabling heap tagging. Heap tagging may not be re-enabled after being disabled.
  M_HEAP_TAGGING_LEVEL_NONE = 0,
  // Address-only tagging. Heap pointers have a non-zero tag in the most significant byte which is
  // checked in free(). Memory accesses ignore the tag.
  M_HEAP_TAGGING_LEVEL_TBI = 1,
  // Enable heap tagging if supported, at a level appropriate for asynchronous memory tag checks.
  M_HEAP_TAGGING_LEVEL_ASYNC = 2,
  // Enable heap tagging if supported, at a level appropriate for synchronous memory tag checks.
  M_HEAP_TAGGING_LEVEL_SYNC = 3,
}HeapTaggingLevel;

// Manipulates bionic-specific handling of memory allocation APIs such as
// malloc. Only for use by the Android platform itself.
//
// On success, returns true. On failure, returns false and sets errno.
extern bool android_mallopt(int opcode, void* arg, size_t arg_size);

```

****

**Comment by Lzhiyong** [comment]
简化版本
mallopt_hook.c
```cpp
#include <stdio.h>
#include <errno.h>

// hook android_mallopt function
// disable heap pointer tagging
void __attribute__((constructor)) mallopt_hook(void) {
    int tag_level = 0;
    if(!android_mallopt(8, &tag_level, sizeof(tag_level))) {
        printf("ERROR: could not disable heap pointer tagging, %s\n", strerror(errno));
    }
}
```

**Comment by lateautumn233** [comment]
那strace能不能获得一些相关的东西，感觉好迷

**Comment by lateautumn233** [comment]
![Screenshot_2021-07-19-20-18-33-510_com termux](https://user-images.githubusercontent.com/63851402/126158640-788b3fe7-a29d-4d65-96b4-f6997869c74f.jpg)
神奇的事情发生了
我编译那个简化版源码正常了

**Comment by lateautumn233** [comment]
![Screenshot_2021-07-19-20-24-39-174_com termux](https://user-images.githubusercontent.com/63851402/126159355-31892020-136d-495b-a82f-0d0ce0dbea0e.jpg)
另外可能就是这个函数没有实现，然后他禁不了tagged pointer
可能是吧，我不怎么懂艹语言

**Comment by Lzhiyong** [comment]
把这个函数在前面声明一下就可以了

mallopt_hook.c
```cpp
#include <stdio.h>
#include <errno.h>
#include <stdbool.h>

// Manipulates bionic-specific handling of memory allocation APIs such as
// malloc. Only for use by the Android platform itself.
//
// On success, returns true. On failure, returns false and sets errno.
extern bool android_mallopt(int opcode, void* arg, size_t arg_size);

// hook android_mallopt function
// disable heap pointer tagging
void __attribute__((constructor)) mallopt_hook(void) {
    int tag_level = 0;
    if(!android_mallopt(8, &tag_level, sizeof(tag_level))) {
        printf("ERROR: could not disable heap pointer tagging, %s\n", strerror(errno));
    }
}

```

**Comment by lateautumn233** [comment]
![Screenshot_2021-07-19-20-43-35-772_com termux](https://user-images.githubusercontent.com/63851402/126161492-ffb0d829-dcf2-4640-a48c-59e8146ae4f2.jpg)
奇奇怪怪的报错

**Comment by jianfeng6** [comment]
安卓11报错0xffffff我只有安卓的设备

**Comment by Lzhiyong** [comment]
参考官方编译教程，https://github.com/termux/termux-packages/tree/master/packages/openjdk-17，Termux&nbsp;现在自带openjdk-17，但是用Java17编译安卓app有一些问题，其实你编译java11会好一点，毕竟google已经支持!
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年8月1日(星期天)&nbsp;中午1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[Lzhiyong/termux-ndk]&nbsp;编译openjdk12失败&nbsp;(#47)



 
安卓11报错0xffffff我只有安卓的设备
 
&mdash;

**Comment by Lzhiyong** [comment]
> 安卓11报错0xffffff我只有安卓的设备

参考官方编译方法[openjdk-17](https://github.com/termux/termux-packages/tree/master/packages/openjdk-17)，Termux现在自带openjdk-17，但是用Java17 编译安卓app目前有一些问题，我也无法解决，还是建议你编译openjdk-11

**Comment by jianfeng6** [comment]
我用的就是openjdk-11但他报错图片以下的错误gradle版本为6.8.3不知道是gradle的问题还是安卓11的问题 我向我朋友借了一个安卓10的手机 完全可以运行 用的是openjdk-11 gradle版本为6.8.3但是一用gradle7.1.1就不行了 不知道是什么错误



---原始邮件---
***@***.***>
发送时间:2021年8月1日(星期天) 下午2:33
***@***.***>;
主题: [Lzhiyong/termux-ndk] 编译openjdk12失败 (#47)


  安卓11报错0xffffff我只有安卓的设备
  参考官方编译方法openjdk-17，Termux现在自带openjdk-17，但是用Java17 编译安卓app目前有一些问题，我也无法解决，还是建议你编译openjdk-11
－

**Comment by jianfeng6** [comment]
---原始邮件---
***@***.***&gt;
发送时间:2021年8月1日(星期天)&nbsp;下午2:33
***@***.***&gt;;
主题:&nbsp;[Lzhiyong/termux-ndk]&nbsp;编译openjdk12失败&nbsp;(#47)


&nbsp;&nbsp;安卓11报错0xffffff我只有安卓的设备
&nbsp;&nbsp;参考官方编译方法openjdk-17，Termux现在自带openjdk-17，但是用Java17&nbsp;编译安卓app目前有一些问题，我也无法解决，还是建议你编译openjdk-11
－
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,&nbsp;view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;or&nbsp;unsubscribe.

**Comment by jianfeng6** [comment]
@Lzhiyong 你是安卓11吗我是新手搞得都想放弃了

**Comment by Lzhiyong** [comment]
> @Lzhiyong 你是安卓11吗我是新手搞得都想放弃了

我的是安卓10，没刷11，所以不太清楚，你问下上面那位哥们，能否正常运行，他用的是11

**Comment by jianfeng6** [comment]
没有那个文件是怎么回事
---原始邮件---
***@***.***&gt;
发送时间:2021年8月1日(星期天)&nbsp;晚上10:57
***@***.***&gt;;
主题:&nbsp;[Lzhiyong/termux-ndk]&nbsp;编译openjdk12失败&nbsp;(#47)


***@***.***&nbsp;你是安卓11吗我是新手搞得都想放弃了
&nbsp;&nbsp;我的是安卓10，没刷11，所以不太清楚，你问下上面那位哥们，能否正常运行，他用的是11
－
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,&nbsp;view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;or&nbsp;unsubscribe.

**Comment by cxyzzz** [comment]
> 把这个函数在前面声明一下就可以了
> 
> mallopt_hook.c
> 
> ```c++
> #include <stdio.h>
> #include <errno.h>
> #include <stdbool.h>
> 
> // Manipulates bionic-specific handling of memory allocation APIs such as
> // malloc. Only for use by the Android platform itself.
> //
> // On success, returns true. On failure, returns false and sets errno.
> extern bool android_mallopt(int opcode, void* arg, size_t arg_size);
> 
> // hook android_mallopt function
> // disable heap pointer tagging
> void __attribute__((constructor)) mallopt_hook(void) {
>     int tag_level = 0;
>     if(!android_mallopt(8, &tag_level, sizeof(tag_level))) {
>         printf("ERROR: could not disable heap pointer tagging, %s\n", strerror(errno));
>     }
> }
> ```

Android 11的时候使用这个方法成功屏蔽了，12上用不了，报错提示Operation not supported on transport endpoint
