### ISSUE TITLE
AGDK

### ISSUE THREAD

**Issue by nikey02** [Lzhiyong/termux-ndk#48]
Hey please can you try AGDK for termux ?
If you have time
Here is link 
https://android.googlesource.com/platform/frameworks/opt/gamesdk/

**Comment by Lzhiyong** [comment]
Well, I can try if I have enough time later, but I don’t guarantee that the compilation will succeed

**Comment by nikey02** [comment]
Sure 
I think there no need for that 
On official website AGDK libraries are not platform specific 
Although I didn't try they are 2Gb in size 
May be you can download and try with termux-ndk and make example .
