### ISSUE TITLE
ndk static compilation error

### ISSUE THREAD

**Issue by Lzhiyong** [Lzhiyong/termux-ndk#49]
there are some problems with static compilation for Android api level < 29

> executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic                                            
> Aborted

How to fix (there are two ways)
* use [align_fix.py](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/align_fix.py)(only arm/arm64), execute the command `align_fix.py your executable file`

* use ndk-r21e sysroot, specify `--sysroot=/path/to/ndk-r21e/sysroot`, this way is recommended, don't directly replace the sysroot of r23 with the sysroot of r21e

**Comment by ytxyyt** [comment]
开发发一下完整指令，或者图片，我不太明白
