### ISSUE TITLE
Can you create a release of this please

### ISSUE THREAD

**Issue by davemackintosh** [Lzhiyong/termux-ndk#5]
Using Github releases, can you package this up please as I cannot get this to compile/link properly on my devices or a simulator.

**Comment by Lzhiyong** [comment]
> Using Github releases, can you package this up please as I cannot get this to compile/link properly on my devices or a simulator.

I have released ndk r21 version！
![Screenshot_2020-07-03-13-38-06-908_com android chrome](https://user-images.githubusercontent.com/36750502/86435697-24680500-bd33-11ea-9e86-926bc0d8eca8.jpg)

**Comment by davemackintosh** [comment]
Oh! Sorry, for some reason I missed that when I wax looking for it. Sorry!
