### ISSUE TITLE
aapt build ?

### ISSUE THREAD

**Issue by jmarcgit** [Lzhiyong/termux-ndk#51]

**Comment by jmarcgit** [comment]
Hi,

I would like to know where you found the aapt2 source code of the maven package com.android.ttols.build.aapt please ?

**Comment by Lzhiyong** [comment]
see issue #50

**Comment by jmarcgit** [comment]
Thanks I was thinking that the sources of SDK were not up to date. Version of aapt2 is always 2.19

Sharing my Android gradle.settings 
`dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google {
            content {
            excludeModule "com.android.tools.build", "aapt2"
            }
        }
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        flatDir {
            dirs '/mnt/chromeos/GoogleDrive/MyDrive/Dev/AndroidProjects/arm64/aapt2'
        }
    }
}
rootProject.name = "My Application"
include ':app'`

Gradle will retrieve the aapt2 module from the local flatDir folder. All you need to do is to drop the modified jar and the pom files into the folder. Simple and permanent fix.

**Comment by Lzhiyong** [comment]
I have compiled the latest source code of aapt2 from [https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2](https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2)

but there are some problems with AGP 7.0.2
> AAPT unknown option '--source-path'

there is no such option in the aapt2 source code, but in `builder-7.0.2.jar` does have this option, see [https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/builder/src/main/java/com/android/builder/internal/aapt/v2/AaptV2CommandBuilder.kt](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/builder/src/main/java/com/android/builder/internal/aapt/v2/AaptV2CommandBuilder.kt)

I don't konw how to fix it

**Comment by jmarcgit** [comment]
Yeah the 2.19 version of aapt2 is the latest available. I think this is exactly the same you included in the 4.1.2 jar file
AGP 4.2 is not working for similar reasons. We are stuck with 4.1.2 for a while.

I opened an feature request at Android asking to  providie ARM64 binaries for SDK and NDK. I'm using an arm chomebook. Most of your binaries are working fine except the ones thata re dynamically linked with libc. (Android doesn't use the standard Linux GLIBC)

But for now I can build Android apps and I can use an x86 machine for the native code. That's not too bad.

**Comment by Lzhiyong** [comment]
see #53 for support AGP-7.0.x
