### ISSUE TITLE
aapt2 source-path error

### ISSUE THREAD

**Issue by Lzhiyong** [Lzhiyong/termux-ndk#53]
When compiling the Android app with AGP-7.0.x, you will encounter an  `--source-path` error from aapt2
> AAPT unknown option '--source-path'

This option is currently doing nothing in  `builder-7.0.x.jar`, so I added this option in  `base/tools/aapt2/cmd/Compile.h`
```cpp
...
bool legacy_mode = false;
// --source-path option
bool source_path = false;
// See comments on aapt::ResourceParserOptions.
bool preserve_visibility_of_styleables = false;
bool verbose = false;
...

AddOptionalSwitch("--legacy", "Treat errors that used to be valid in AAPT as warnings",
    &options_.legacy_mode);
// --source-path do nothing
AddOptionalSwitch("--source-path", "Currently this option do nothing",
    &options_.source_path);
...

```
download the aapt2 form [sdk-tools](https://github.com/Lzhiyong/sdk-tools/releases)

there is no such option in the aapt2 source code, but in `builder-7.0.x.jar` does have this option, see [https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/builder/src/main/java/com/android/builder/internal/aapt/v2/AaptV2CommandBuilder.kt](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/builder/src/main/java/com/android/builder/internal/aapt/v2/AaptV2CommandBuilder.kt)

**Comment by ANIL80531** [comment]
### Thanks🥳🥳

You have not mentioned which aapt2 fiile to copy i copied aap2 in sdk-tool-source.zip which didn't worked but aapt2 file in sdk-static-aarch64.zip it worked.

**Comment by Lzhiyong** [comment]
> ### Thanks🥳🥳
> You have not mentioned which aapt2 fiile to copy i copied aap2 in sdk-tool-source.zip which didn't worked but aapt2 file in sdk-static-aarch64.zip it worked.

the

**Comment by Lzhiyong** [comment]
> ### Thanks🥳🥳
> You have not mentioned which aapt2 fiile to copy i copied aap2 in sdk-tool-source.zip which didn't worked but aapt2 file in sdk-static-aarch64.zip it worked.

@ANIL80531  the sdk-tool-source.zip has been updated because I forgot to patch it before.
