### ISSUE TITLE
ERROR FOR MAKING GTA SAN APK

### ISSUE THREAD

**Issue by Lufzyyy** [Lzhiyong/termux-ndk#54]
error for libsamp.so?

**Comment by Lzhiyong** [comment]
![IMG_20211003_155221](https://user-images.githubusercontent.com/36750502/135745111-a45bc27a-99fb-4681-a304-fa565dc7b90e.jpg)


Search SAMPMobile on Github and use `/path/to/android-ndk-r23/ndk-build` to compile the libsamp.so

Application.mk
```Android.mk
APP_ABI := armeabi-v7a
APP_PLATFORM := android-16
APP_MODULES := samp
APP_STL := c++_static
```

**Comment by Lzhiyong** [comment]
This is not a problem with ndk, there may be a problem with your source code！
