### ISSUE TITLE
无法运行jdk

### ISSUE THREAD

**Issue by ytxyyt** [Lzhiyong/termux-ndk#55]
下载的你的那个jdk
![Screenshot_20211004_190926_com termux](https://user-images.githubusercontent.com/84581911/135842429-0cd29c41-a6b8-4fbb-8203-f3584fdf1c4c.jpg)

**Comment by Lzhiyong** [comment]
getloadavg 需要安卓10，编译的时候用的是29的api进行编译的，因此只能运行在Android 10以上
