### ISSUE TITLE
Simplifying installation

### ISSUE THREAD

**Issue by sterling0x1** [Lzhiyong/termux-ndk#6]
Great project but building it all from scratch seems extremely time consuming. Aarch64  Linux system on android can be achieved by installing Kali Nethunter or use Atilo in termux. They both create chroot on Android system and have access to native aarch64 apt packages (what you normally get if you're on a raspberry pi for example).
Already have Android SDK packages, full llvm, and cmake.
I was wondering if I could get around all the building process and have android-ndk installed in a simpler way.

Possibly to Kali chroot instead of termux.
Thanks a lot!

**Comment by Lzhiyong** [comment]
> Great project but building it all from scratch seems extremely time consuming. Aarch64 Linux system on android can be achieved by installing Kali Nethunter or use Atilo in termux. They both create chroot on Android system and have access to native aarch64 apt packages (what you normally get if you're on a raspberry pi for example).
> Already have Android SDK packages, full llvm, and cmake.
> I was wondering if I could get around all the building process and have android-ndk installed in a simpler way.
> 
> Possibly to Kali chroot instead of termux.
> Thanks a lot!

Sorry, there is no simpler installation yet, because ndk is still too big. If google can remove some useless tools, maybe it can!
