### ISSUE TITLE
please release termux-ndk-r21d to support termux-packages

### ISSUE THREAD

**Issue by zxq432** [Lzhiyong/termux-ndk#60]
use the termux proot-distro archlinux login with --isolated to build proot from termux-packages, when using the termux-ndk-r23 to build proot, find some issues
1. the termux-ndk-r23 lacks some ld, ld.gold. ld.* files termux-packages required, and failed, need do ln -s lld to all needed ld* files as a workaround.
2. the scripts/build/termux_step_setup_toolchain.sh patch files in sysroot, patch fail for a file a failed

the termux-ndk-r21d is needed. please release it again.

**Comment by Lzhiyong** [comment]
The ndk-r21d has been removed, please wait for termux official support ndk-r23
