### ISSUE TITLE
为什么我的gradle输出不是彩色的，没有进度条呢？在linu有进度条和颜色

### ISSUE THREAD

**Issue by ytxyyt** [Lzhiyong/termux-ndk#61]
![Screenshot_20211006_051718_com termux](https://user-images.githubusercontent.com/84581911/136104173-f97a3e29-ba0d-4873-a899-59bd8ddce1f6.jpg)

**Comment by Lzhiyong** [comment]
gradle --console=rich

**Comment by ytxyyt** [comment]
> gradle --console=rich

每次打包都添加这个属性，太麻烦了吧，有没有全局对所有项目都生效的方法
