### ISSUE TITLE
AAPT2: unknown flag --source-path

### ISSUE THREAD

**Issue by masterjavaofficial** [Lzhiyong/termux-ndk#67]
Hello sir.

I somehow managed to get aapt2 for my armeabi-v7a architecture phone. Then I packed it into a jar and replaced the incompatible one in gradle cache dir with it. But now, when I enter ```gradle build```, this error occurs. Any idea how to resolve this? Please help me.

I'm using AGP 7.0.3 in build.gradle, and the gradle version is 7.2 which is the latest available version in Termux. The aapt2 version I managed to get is version 2.19.

![Screenshot_2021-10-14-22-42-45-803_com termux](https://user-images.githubusercontent.com/78401450/137361562-f86c9d4a-1413-4d7b-bdf2-e936a3f74434.jpg)

**Comment by Lzhiyong** [comment]
see issue #53
