### ISSUE TITLE
不支持ndk-build吗

### ISSUE THREAD

**Issue by jianfeng6** [Lzhiyong/termux-ndk#70]
![Screenshot_2021-11-02-14-56-56-254_com termux](https://user-images.githubusercontent.com/71310844/139800256-7773bfa3-2850-4fcc-bea3-c03936b4d8bf.jpg)
![Screenshot_2021-11-02-14-56-50-084_bin mt plus](https://user-images.githubusercontent.com/71310844/139800274-99813852-3838-4640-b9d9-b65ba563efd9.jpg)

**Comment by Lzhiyong** [comment]
![IMG_20211102_184105](https://user-images.githubusercontent.com/36750502/139832184-53d345e1-616b-441e-b7b8-115e9a632139.jpg)

我使用的是ubuntu，没有问题
