### ISSUE TITLE
release里面是直接开箱即用?还是得完整走一遍编译流程

### ISSUE THREAD

**Issue by maru7777** [Lzhiyong/termux-ndk#71]
另README里有
(注释)sync finish, exit ArchLinux
exit
可是 之前并没有看到 proot-distro login ArchLinux 这里怎么就退出了呢
而且从接下来的命令使用的路径来看,的确没进到ArchLinux里操作 
这就很奇怪了?
另外可以用termux里的ubuntu系统来代替ArchLinux吗?

**Comment by Lzhiyong** [comment]
README忘记修改了，因为之前使用的是另外一个ArchLinux并非Termux自带的proot-distro，以前官方仓库也没有proot-distro

可以使用ubuntu替代，不过还是建议在PC上进行编译，在手机上编译花费时间实在是太长了，这里的教程只是一个参考，只需把clang和llvm交叉编译了，然后替换掉NDK里面的llvm就可以了，sysroot是不需要我们自己编译的

release里面是编译完成了的，不需要重新进行编译

**Comment by maru7777** [comment]
> README忘记修改了，因为之前使用的是另外一个ArchLinux并非Termux自带的proot-distro，以前官方仓库也没有proot-distro
> 
> 可以使用ubuntu替代，不过还是建议在PC上进行编译，在手机上编译花费时间实在是太长了，这里的教程只是一个参考，只需把clang和llvm交叉编译了，然后替换掉NDK里面的llvm就可以了，sysroot是不需要我们自己编译的
> 
> release里面是编译完成了的，不需要重新进行编译

明白,多谢了
