### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by masterjavaofficial** [Lzhiyong/termux-ndk#73]
Can you build a thing for Android Architecture to be able to use in Termux?
I just know Java and its build system, not any C/++. Now its about a month, and still I'm facing a lot of trouble to build it... Its [openjfx](https://openjfx.io), which is a Java's cross platfrom graphics framework/library (like Swing) used to build desktop apps using. It uses gtk for rendering in Linux. The full build instructions for Linux can be found here: https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX#BuildingOpenJFX-Ubuntu18.04.

Would you please build it for armv7a, linking every dependencies statically? Please...

For me, it shows this error when trying to build with gradle in Termux: (see full command [here](https://github.com/termux/termux-packages/issues/7464#issuecomment-966386911))

```
...
...
> Task :graphics:linkDecoraNativeShadersLinux FAILED
ld.lld: error: unable to find library -lc++_shared
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':graphics:linkDecoraNativeShadersLinux'.
> Process 'command 'g++'' finished with non-zero exit value 1
...
...
```

**Comment by Lzhiyong** [comment]
![IMG_20211121_104140](https://user-images.githubusercontent.com/36750502/142747598-5029acad-a535-4427-887b-830e7519d1b6.jpg)

![IMG_20211121_104249](https://user-images.githubusercontent.com/36750502/142747605-4ad61e85-078b-45b1-ac77-ef162feac584.jpg)

Can be compiled successfully for Android platform, but only aarch

**Comment by masterjavaofficial** [comment]
Ahh, 

> ![IMG_20211121_104140](https://user-images.githubusercontent.com/36750502/142747598-5029acad-a535-4427-887b-830e7519d1b6.jpg)
> 
> ![IMG_20211121_104249](https://user-images.githubusercontent.com/36750502/142747605-4ad61e85-078b-45b1-ac77-ef162feac584.jpg)
> 
> Can be compiled successfully for Android platform.

No, targetting Android is not the solution. If you target Android, its builds libraries which you can use to build Android apps using JavaFX. But what I need is for Linux, to build desktop apps. Both are very different things.

**Comment by Lzhiyong** [comment]
> No, targetting Android is not the solution. If you target Android, its builds libraries which you can use to build Android apps using JavaFX. But what I need is for Linux, to build desktop apps. Both are very different things.

For linux, I think it would be better to use poot-distro

**Comment by masterjavaofficial** [comment]
> For linux, I think it would be better to use proot-distro

I used to. But as Termux already has openjdk-17 and gradle, it would be greater to use OpenJFX directly. Actually openjfx is a part of official Java SE (same as AWT and Swing), but is detached from the JDK mainline project to get more attention and improvements. So it has to be built differently, and then add in the place of Java SE libraries.

**Comment by Lzhiyong** [comment]
Building a UI toolkit is a complicated thing, you should ask xeffyr for help to integrate openjfx into openjdk-17.

**Comment by masterjavaofficial** [comment]
> Building a UI toolkit is a complicated thing, you should ask xeffyr for help to integrate openjfx into openjdk-17.

I asked, but no response from there. They seems not to give any attention to Java things.

**Comment by masterjavaofficial** [comment]
However, as you've built for Android, can you provide me those builds?

**Comment by Lzhiyong** [comment]
> However, as you've built for Android, can you provide me those builds?

only aarch64, seem not support armv7a

**Comment by masterjavaofficial** [comment]
> only aarch64, seem not support armv7a

Ohh. Very sad that I don't have a PC. 😔
