### ISSUE TITLE
We need support for 32 bit devices for ndk

### ISSUE THREAD

**Issue by freindlytech** [Lzhiyong/termux-ndk#74]
Buddy You are the best developer who is like angle to everyone which doesn't have pc , love your work bro , can you please provide ndk r23 support for 32 bit. You are really great who is working and like god to those without pc , Don't leave us never and ever , we will 100% support you.

**Comment by Lzhiyong** [comment]
Well, it’s a bit troublesome, there is not enough time to do this at the moment, I will consider this in the next update.

**Comment by freindlytech** [comment]
Thanks For Answering , We will get Update every time  from you of every sdktools made by you for aarch64 that is  released by google every time google launched a new version of tools like aapt2  ?? If Yes Then you are like a god to us , I will always support you in anything , love you buddy

**Comment by freindlytech** [comment]
Thanks For Answering , We will get Update every time  from you of every sdktools made by you for aarch64 that is  released by google every time google launched a new version of tools like aapt2  ?? If Yes Then you are like a god to us , I will always support you in anything , love you buddy
