### ISSUE TITLE
A Very Important Question

### ISSUE THREAD

**Issue by freindlytech** [Lzhiyong/termux-ndk#75]
We will get Update every time  from you of every sdktools made by you for aarch64 that is  released by google every time google launched a new version of tools like aapt2  ?? If Yes Then you are like a god to us , I will always support you in anything , love you buddy

**Comment by Lzhiyong** [comment]
Um, I can’t guarantee this, because I have other things to do. The purpose of open source is to hope that you can compile by yourself without relying on me.

**Comment by freindlytech** [comment]
Ok I can Understand, But Plz Don't leave us sir , I am requesting plz don't go anywhere we will always support you in anything , We Love  You Sir , we need you don't break our hope sir 🙏🙏🙏🙏🙏

**Comment by Randomxdp** [comment]
Bro almost anybody can build the ndk on termux
You just need a good amount of storage and decent ram he even gave the patches to patch any ndk version that you want

**Comment by freindlytech** [comment]
Can you plz teach me how to do it I need it plz help

**Comment by Randomxdp** [comment]
Just install a proot distro and install repo in it to clone the repos in termux home dir , patch the repo and then build it from termux

**Comment by Lzhiyong** [comment]
> Just install a proot distro and install repo in it to clone the repos in termux home dir , patch the repo and then build it from termux

If you are compiling for arm, you need to do it on the pc, not on the device, because I don’t provide a 32-bit ndk, so we need to use Google’s official ndk to compile llvm-toolchain for armv7a.
