### ISSUE TITLE
Love2d fails

### ISSUE THREAD

**Issue by Vixeliz** [Lzhiyong/termux-ndk#77]
![Screenshot_20211207-015215_Termux](https://user-images.githubusercontent.com/38061852/144988462-372436cb-8d76-4ce8-b9b2-47e73218950b.jpg)

This happens with love2d ive updated the ndk and sdk(with the updated sdk-tools) and followed along the build-app guide. However i still get unkown architecture. (By the way this isnt related to my last issue at all) any help would be appreciated thanks :)

**Comment by Lzhiyong** [comment]
I have fixed it, please download again.

modify the Application.mk
```Android.mk
# min sdk api level 16
APP_PLATFORM := 16
```

**Comment by Vixeliz** [comment]
Dowload what again the ndk or sdk?

**Comment by Lzhiyong** [comment]
> Dowload what again the ndk or sdk?

the ndk

**Comment by Vixeliz** [comment]
Alright will do. Is it in releases or do i need to compile?

**Comment by Lzhiyong** [comment]
> 

no need to compile, just download the ndk-r23b again

**Comment by Lzhiyong** [comment]
> Alright will do. Is it in releases or do i need to compile?

no need to compile, just download the ndk-r23b again.

**Comment by Vixeliz** [comment]
Awesome thanks for the quick response u are an awesome maintainer. Trying now

**Comment by Vixeliz** [comment]
Now working thank you so much!!!
