### ISSUE TITLE
jdk11

### ISSUE THREAD

**Issue by yinli155** [Lzhiyong/termux-ndk#79]
Android 12 appears with jdk11 Pointer tag for 0x7423b47c60 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'. Aborted

**Comment by Lzhiyong** [comment]
> Android 12 appears with jdk11 Pointer tag for 0x7423b47c60 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'. Aborted

see termux-packages issues [#7332](https://github.com/termux/termux-packages/issues/7332)

**Comment by yutong-yt** [comment]
> > Android 12 出现 jdk11 指针标记 0x7423b47c60 被截断，请参阅“ https://source.android.com/devices/tech/debug/tagged-pointers ”。中止
> 
> 请参阅 termux-packages 问题[#7332](https://github.com/termux/termux-packages/issues/7332)

看不到对方的方法，就看懂了一个更换32位的，但是没有32位的ndk

**Comment by Teeskid** [comment]
java --version
Error: dl failure on line 598
Error: failed /data/data/com.termux/files/usr/share/openjdk-11.0.12/lib/server/libjvm.so, because dlopen failed: cannot locate symbol "getloadavg" referenced by "/data/data/com.termux/files/usr/share/openjdk-11.0.12/lib/server/libjvm.so"...

**Comment by Lzhiyong** [comment]
> java --version Error: dl failure on line 598 Error: failed /data/data/com.termux/files/usr/share/openjdk-11.0.12/lib/server/libjvm.so, because dlopen failed: cannot locate symbol "getloadavg" referenced by "/data/data/com.termux/files/usr/share/openjdk-11.0.12/lib/server/libjvm.so"...

`getloadavg` requers android10+

**Comment by Teeskid** [comment]
Thanks, So I can't use jdk 11 on pie
