### ISSUE TITLE
Ndk prebuilt request - llvm toolchain 

### ISSUE THREAD

**Issue by Rockysri** [Lzhiyong/termux-ndk#81]
It's already 5 GB , and it's still downloading. How much is the size of the source from that repo. (How long will it take ?.

**Comment by Lzhiyong** [comment]
about 16GB, how long depends on your internet speed.p

**Comment by Lzhiyong** [comment]
> It's already 5 GB , and it's still downloading. How much is the size of the source from that repo. (How long will it take ?.

about 16GB, how long depends on your internet speed.p

**Comment by Lzhiyong** [comment]
> It's already 5 GB , and it's still downloading. How much is the size of the source from that repo. (How long will it take ?.

about 16GB, how long depends on your internet speed.

**Comment by Rockysri** [comment]
Could you post the built android ndk . So that the messy process can be avoided. And I can get ready to build app. Thank you for the reply.

**Comment by Lzhiyong** [comment]
> Could you post the built android ndk . So that the messy process can be avoided. And I can get ready to build app. Thank you for the reply.

download the prebuilt toolchain from [release](https://github.com/Lzhiyong/termux-ndk/releases)
