### ISSUE TITLE
Clang120++ not found

### ISSUE THREAD

**Issue by Saikatsaha1996** [Lzhiyong/termux-ndk#84]
Any solution for this?
![IMG_20220113_134858](https://user-images.githubusercontent.com/72664192/149364609-65fbe4a6-2a70-4340-9460-2daec8d3f641.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2022-01-13-23-28-09-190_com termux](https://user-images.githubusercontent.com/72664192/149383907-8567a824-a78d-4c6c-bb1b-998a2d3200a9.jpg)
aarch64-linux-android-clang++ found but can't found clang120++ how to solve?

But in my installation dir available clang120++
![Screenshot_2022-01-13-22-09-17-298_com termux](https://user-images.githubusercontent.com/72664192/149384144-9d9f1cc7-0dde-4f95-bb58-117f3cee409b.jpg)

**Comment by Lzhiyong** [comment]
Do not modify the toolchain path, the following method is recommended
```bash
# for example: 
# architecture: aarch64
# platform: android-30

# the ndk toolchain full path
export NDK_TOOLCHAIN=/path/to/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64

export CC=$NDK_TOOLCHAIN/aarch64-linux-android30-clang

export CXX=$NDK_TOOLCHAIN/aarch64-linux-android30-clang++

...
```

Note that using proot-distro is not recommended.

**Comment by Saikatsaha1996** [comment]
> Do not modify the toolchain path, the following method is recommended
> 
> ```shell
> # for example: 
> # architecture: aarch64
> # platform: android-30
> 
> # the ndk toolchain full path
> export NDK_TOOLCHAIN=/path/to/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64
> 
> export CC=$NDK_TOOLCHAIN/aarch64-linux-android30-clang
> 
> export CXX=$NDK_TOOLCHAIN/aarch64-linux-android30-clang++
> 
> ...
> ```
> 
> Note that using proot-distro is not recommended.

I am using it for experimental purpose
But thank you i will trying!..
So i should change also basrc ..
Please suggest me .. 
![Screenshot_2022-01-14-08-33-36-081_com termux](https://user-images.githubusercontent.com/72664192/149444606-2b2329f3-e3fb-42fe-959b-2d17f1cd4533.jpg)

**Comment by Lzhiyong** [comment]
Just write it in build.sh, no need to change the bashrc.

**Comment by Saikatsaha1996** [comment]
> Just write it in build.sh, no need to change the bashrc.

Oky 🤗 thankyou

**Comment by Saikatsaha1996** [comment]
> Just write it in build.sh, no need to change the bashrc.

I should build my own ndk ?
Or i can use your prebuilt zip
By the way I am using your prebuilt zip..
Just see what happening , what mistake i done?
![IMG_20220114_102138](https://user-images.githubusercontent.com/72664192/149453914-11a05ada-afec-4293-8563-ad3fcba08d25.jpg)
![IMG_20220114_102604](https://user-images.githubusercontent.com/72664192/149453925-c83a758f-3fc4-4cfb-84bc-613edfdd6a5f.jpg)

**Comment by Saikatsaha1996** [comment]
> Just write it in build.sh, no need to change the bashrc.

Which build.sh file ? I thought wrong

**Comment by Saikatsaha1996** [comment]
![Screenshot_2022-01-14-12-53-34-013_tech ula](https://user-images.githubusercontent.com/72664192/149467807-6dcbf09f-c1bf-4300-8343-05c3cf287565.jpg)
![Screenshot_2022-01-14-12-54-20-797_tech ula](https://user-images.githubusercontent.com/72664192/149467855-9d10e5a1-a39e-4b1d-a310-a3fe13df8e59.jpg)
New update

**Comment by Lzhiyong** [comment]
![Screenshot_2022-01-14-15-50-36-825_com termux](https://user-images.githubusercontent.com/36750502/149471461-7eb3575b-c974-4213-bfaa-ff145958638d.jpg)


Use clang to compile simple cpp file and see what happens?

**Comment by Saikatsaha1996** [comment]
> ![Screenshot_2022-01-14-15-50-36-825_com termux](https://user-images.githubusercontent.com/36750502/149471461-7eb3575b-c974-4213-bfaa-ff145958638d.jpg)
> 
> Use clang to compile simple cpp file and see what happens?

Okay

**Comment by Saikatsaha1996** [comment]
> > ![Screenshot_2022-01-14-15-50-36-825_com termux](https://user-images.githubusercontent.com/36750502/149471461-7eb3575b-c974-4213-bfaa-ff145958638d.jpg)
> > Use clang to compile simple cpp file and see what happens?
> 
> Okay

Test.cpp comnd not found..

but same problem happened also pure termux.. not proot-distro..
![Screenshot_2022-01-14-14-42-30-348_com termux](https://user-images.githubusercontent.com/72664192/149490030-80832ded-fbc5-449b-8c38-48fa6493591b.jpg)

**Comment by Lzhiyong** [comment]
not `/**/bin/aarch64-linux-android-clang++` 
the correct should be `/**/bin/aarch64-linux-android28-clang++` for api level 28

note: 
API=28
aarch64-linux-android$API-clang++

I think the scons build script need to be patched.

**Comment by Saikatsaha1996** [comment]
Okay trying

**Comment by Lzhiyong** [comment]
or yon can try
```bash
export NDK_TOOLCHAIN=/path/to/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64

export CC=$NDK_TOOLCHAIN/clang
export CXX=$NDK_TOOLCHAIN/clang++

# specify the target android-28

``

**Comment by Saikatsaha1996** [comment]
> or yon can try
> 
> ```shell
> export NDK_TOOLCHAIN=/path/to/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64
> 
> CC=$NDK_TOOLCHAIN/bin/clang
> CXX=$NDK_TOOLCHAIN/bin/clang++
> 
> # specify the target
> CFLAGS="--target=aarch64-linux-android28"
> CXXFLAGS="--target=aarch64-linux-android28"
> ```

Okay trying.. actually I am trying to experimental purpose only.. but thank you for your help..

**Comment by Saikatsaha1996** [comment]
> 

![Screenshot_2022-01-14-15-35-51-687_com termux](https://user-images.githubusercontent.com/72664192/149497778-9a39a370-56a3-4a7e-ad9b-68d57052f800.jpg)
![Screenshot_2022-01-14-15-37-04-742_com termux](https://user-images.githubusercontent.com/72664192/149497828-96993bf5-f670-4af8-af8a-d68e8c5ffac6.jpg)

**Comment by Lzhiyong** [comment]
the SConscript need to be patched.

the path `aarch64-linux-android-/data/data/**/clang++` should be wrong

the correct should be `/data/data/com.termux/files/home/armnn-devenv/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++`

please check the SConscript

**Comment by Saikatsaha1996** [comment]
#
[SConscript.txt](https://github.com/Lzhiyong/termux-ndk/files/7869684/SConscript.txt)
[SConstruct.txt](https://github.com/Lzhiyong/termux-ndk/files/7869685/SConstruct.txt)

**Comment by Lzhiyong** [comment]
> [SConscript.txt](https://github.com/Lzhiyong/termux-ndk/files/7869684/SConscript.txt) [SConstruct.txt](https://github.com/Lzhiyong/termux-ndk/files/7869685/SConstruct.txt)

modify SConstruct 
```python
# line 325 and 326
env['CC'] = env['compiler_cache'] + c_compiler
env['CXX'] = env['compiler_cache'] + cpp_compiler
```

I have compiled successfully！

![Screenshot_2022-01-14-19-05-11-042_com termux](https://user-images.githubusercontent.com/36750502/149506471-84c1d01e-2a29-4537-812c-b2b8e0dbea66.jpg)


![Screenshot_2022-01-14-19-14-04-767_com termux](https://user-images.githubusercontent.com/36750502/149506744-3c07b684-4a8f-4918-b090-0c9f7cca489d.jpg)

**Comment by Saikatsaha1996** [comment]
> > [SConscript.txt](https://github.com/Lzhiyong/termux-ndk/files/7869684/SConscript.txt) [SConstruct.txt](https://github.com/Lzhiyong/termux-ndk/files/7869685/SConstruct.txt)
> 
> modify SConstruct
> 
> ```python
> # line 325 and 326
> env['CC'] = env['compiler_cache'] + c_compiler
> env['CXX'] = env['compiler_cache'] + cpp_compiler
> ```
> 
> I have compiled successfully！
> 
> ![Screenshot_2022-01-14-19-05-11-042_com termux](https://user-images.githubusercontent.com/36750502/149506471-84c1d01e-2a29-4537-812c-b2b8e0dbea66.jpg)
> 
> ![Screenshot_2022-01-14-19-16-40-524_com termux](https://user-images.githubusercontent.com/36750502/149507252-aae2b4aa-78f7-480d-aac3-a5cbe17f49a9.jpg)

Okay 👌👌👌👌

**Comment by Saikatsaha1996** [comment]
> > [SConscript.txt](https://github.com/Lzhiyong/termux-ndk/files/7869684/SConscript.txt) [SConstruct.txt](https://github.com/Lzhiyong/termux-ndk/files/7869685/SConstruct.txt)
> 
> modify SConstruct
> 
> ```python
> # line 325 and 326
> env['CC'] = env['compiler_cache'] + c_compiler
> env['CXX'] = env['compiler_cache'] + cpp_compiler
> ```
> 
> I have compiled successfully！
> 
> ![Screenshot_2022-01-14-19-05-11-042_com termux](https://user-images.githubusercontent.com/36750502/149506471-84c1d01e-2a29-4537-812c-b2b8e0dbea66.jpg)
> 
> ![Screenshot_2022-01-14-19-16-40-524_com termux](https://user-images.githubusercontent.com/36750502/149507252-aae2b4aa-78f7-480d-aac3-a5cbe17f49a9.jpg)

Yes now compiling 😍😍😍🤩🤩

Bit got one error how you completed ? 🤩

**Comment by Lzhiyong** [comment]
> Bit got one error how you completed ? 🤩

Werror=0

**Comment by Saikatsaha1996** [comment]
> > [SConscript.txt](https://github.com/Lzhiyong/termux-ndk/files/7869684/SConscript.txt) [SConstruct.txt](https://github.com/Lzhiyong/termux-ndk/files/7869685/SConstruct.txt)
> 
> modify SConstruct
> 
> ```python
> # line 325 and 326
> env['CC'] = env['compiler_cache'] + c_compiler
> env['CXX'] = env['compiler_cache'] + cpp_compiler
> ```
> 
> I have compiled successfully！
> 
> ![Screenshot_2022-01-14-19-05-11-042_com termux](https://user-images.githubusercontent.com/36750502/149506471-84c1d01e-2a29-4537-812c-b2b8e0dbea66.jpg)
> 
> ![Screenshot_2022-01-14-19-16-40-524_com termux](https://user-images.githubusercontent.com/36750502/149507252-aae2b4aa-78f7-480d-aac3-a5cbe17f49a9.jpg)

Ohh now understand why I am getting error 
Werror=1 to 0
Asserts=1 to 0
Build successfully.. but can you tell me what is werror and asserts ?..

**Comment by Saikatsaha1996** [comment]
> > Bit got one error how you completed ? 🤩
> 
> Werror=0

Yes  just done

**Comment by Lzhiyong** [comment]
> Ohh now understand why I am getting error Werror=1 to 0 Asserts=1 to 0 Build successfully.. but can you tell me what is werror and asserts ?..

Please google for details, there are many things you may need to learn! 😄

**Comment by Saikatsaha1996** [comment]
> > Ohh now understand why I am getting error Werror=1 to 0 Asserts=1 to 0 Build successfully.. but can you tell me what is werror and asserts ?..
> 
> Please google for details, there are many things you may need to learn! 😄

Oky but thank you so much..🤗
Actually I don't know about programming language..
But i don't know why I am loving this..

**Comment by Saikatsaha1996** [comment]
![Screenshot_2022-01-14-17-30-39-836_com termux](https://user-images.githubusercontent.com/72664192/149512374-a3897a0a-0de1-4763-a334-9d41eee3433d.jpg)
![Screenshot_2022-01-14-17-30-21-162_com termux](https://user-images.githubusercontent.com/72664192/149512430-c1a7267c-2de5-4ec6-89cc-d01ddf05ddde.jpg)


My error and my comm line 
scons Werror=0 -j8 debug=0 asserts=0 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a

**Comment by Lzhiyong** [comment]
> My error and my comm line scons Werror=0 -j8 debug=0 asserts=0 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a

just warning, since some functions have been deprecated.
warning ≠ error

**Comment by Lzhiyong** [comment]
error: aarch64-linux-android-ar not found

please check the aarch64-linux-android-ar command

or 
pkg install binutils

**Comment by Saikatsaha1996** [comment]
> error: aarch64-linux-android-ar not found
> 
> please check the `aarch64-linux-android-ar` command
> 
> or pkg install binutils

Yey 🤩🤩🤩 hurray building done 😍😍😍
![Screenshot_2022-01-14-18-51-53-984_com termux](https://user-images.githubusercontent.com/72664192/149522012-6bc8fcf7-3b2c-4caf-bd0d-e5eef2c50a84.jpg)

**Comment by Saikatsaha1996** [comment]
> error: aarch64-linux-android-ar not found
> 
> please check the `aarch64-linux-android-ar` command
> 
> or pkg install binutils

Can you give me one more solution please ☺️
Actually i can't set toolchain cmake environment variables.. see this errors.. you can understand..

![Screenshot_2022-04-01-17-41-08-939_com termux](https://user-images.githubusercontent.com/72664192/161260900-211be7cf-da0a-488e-8cb2-354fe78e4285.jpg)
![Screenshot_2022-04-01-17-41-24-573_com termux](https://user-images.githubusercontent.com/72664192/161260908-3b9fb6be-7423-413b-bb4e-53dafd8f9b6c.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2022-04-01-18-40-09-190_com termux](https://user-images.githubusercontent.com/72664192/161270630-7dcff218-c5a3-49e0-9863-e0c31471202a.jpg)

**Comment by Saikatsaha1996** [comment]
> error: aarch64-linux-android-ar not found
> 
> please check the `aarch64-linux-android-ar` command
> 
> or pkg install binutils

Help wanted please getting error too many please give me solution..
Getting error when i trying to build ArmNN with android ndk 
https://github.com/ARM-software/armnn
![Screenshot_2022-04-04-02-23-51-043_com termux](https://user-images.githubusercontent.com/72664192/161448366-e0cd4a32-92fa-4929-8a2a-0e54409edc57.jpg)

**Comment by Saikatsaha1996** [comment]
Happy New year 🎉

Termux ndk supported in `aarch64-linux` os ?

**Comment by Lzhiyong** [comment]
> Happy New year 🎉
> 
> Termux ndk supported in `aarch64-linux` os ?

This requires upstream support, please see [https://github.com/android/ndk/issues/1752](https://github.com/android/ndk/issues/1752)

**Comment by Saikatsaha1996** [comment]
For some confusion.. can you guide me please?

Inside proot Linux i have issue like this..

Can you help?

![IMG_20230501_085219](https://user-images.githubusercontent.com/72664192/235400991-0ac3d5ec-9b1d-40d8-945c-4429a0eedc91.jpg)

**Comment by lzhiyong** [comment]
> For some confusion.. can you guide me please?
> 
> Inside proot Linux i have issue like this..
> 
> Can you help?

you should export clang=/path/to/android-ndk-r24/**/clang, then exec the clang --version

or 
you should exec the CC --version 
because the CC=android-ndk-r24/**/clang

**Comment by Saikatsaha1996** [comment]
> > For some confusion.. can you guide me please?
> > Inside proot Linux i have issue like this..
> > Can you help?
> 
> you should export clang=/path/to/android-ndk-r24/**/clang, then exec the clang --version
> 
> or you should exec the CC --version because the CC=android-ndk-r24/**/clang

Dear need small help from you.. trying to cross compile.. please can you help?

Cpp & LD not available.. and one warning.. how can I solve?

![IMG_20240414_003226](https://github.com/lzhiyong/termux-ndk/assets/72664192/c49c4b60-b952-4dd6-8ab3-2ae38eab78ec)
