### ISSUE TITLE
dx in build-tools 30.0.3

### ISSUE THREAD

**Issue by Mark-Joy** [Lzhiyong/termux-ndk#85]
Hello,
In build-tools 31.0.0 they replace `dx` and `lib/dx.jar` with `d8` and `lib/d8.jar`.
They are still present in 30.0.3
Could you please reupload/provide the download link to android-sdk-30.0.3? or just `dx` and `lib/dx.jar` is enough for me.
Thank you.

**Comment by Lzhiyong** [comment]
> Hello, In build-tools 31.0.0 they replace `dx` and `lib/dx.jar` with `d8` and `lib/d8.jar`. They are still present in 30.0.3 Could you please reupload/provide the download link to android-sdk-30.0.3? or just `dx` and `lib/dx.jar` is enough for me. Thank you.

The dx has been deprecated by google, you should migrate your app to d8, see [https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html](https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html)

if you need build-tools-30.0.3, please use the sdkmanager to download and then replace the aapt2.

**Comment by Mark-Joy** [comment]
Thank you. I just downloaded the build-tools 30.0.3
