### ISSUE TITLE
Ndk error

### ISSUE THREAD

**Issue by RohitVermaOP** [Lzhiyong/termux-ndk#87]
![IMG_20220225_092401](https://user-images.githubusercontent.com/56387351/155669020-ec731aa0-06a6-40f7-a913-47b0aef90101.jpg)

**Comment by RohitVermaOP** [comment]
How to solve this error?

**Comment by Lzhiyong** [comment]
> How to solve this error?

Please use termux's clang and see if you get the same error.

you've given so little information that I can't tell if the error is coming from clang or your build script.

**Comment by RohitVermaOP** [comment]
* What went wrong:                                                Execution failed for task ':app:buildCMakeDebug[armeabi-v7a]'.    > Build command failed.                                             Error while executing process /data/data/com.termux/files/home/android-sdk/cmake/bin/ninja with arguments {-C /storage/emulated/0/AppProjects/TGUi/app/.cxx/Debug/4o1i3n3o/armeabi-v7a tgui}          ninja: Entering directory `/storage/emulated/0/AppProjects/TGUi/app/.cxx/Debug/4o1i3n3o/armeabi-v7a'                                [1/38] Building C object CMakeFiles/tgui.dir/jni.c.o              FAILED: CMakeFiles/tgui.dir/jni.c.o                               /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -Dtgui_EXPORTS -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/lz4 -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -w -std=c11 -DANDROID -D_LARGEFILE_SOURCE=1 -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -ffast-math -Os -funroll-loops -fno-strict-aliasing -fno-math-errno -Wall -fno-rtti -finline-functions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -w -O3 -MD -MT CMakeFiles/tgui.dir/jni.c.o -MF CMakeFiles/tgui.dir/jni.c.o.d -o CMakeFiles/tgui.dir/jni.c.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/jni.c                                           Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [2/38] Building CXX object CMakeFiles/tgui.dir/utilities.cpp.o    FAILED: CMakeFiles/tgui.dir/utilities.cpp.o                       /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -Dtgui_EXPORTS -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/lz4 -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -ffast-math -Os -funroll-loops -fno-strict-aliasing -fno-math-errno -Wall -fno-rtti -finline-functions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -w -O3 -MD -MT CMakeFiles/tgui.dir/utilities.cpp.o -MF CMakeFiles/tgui.dir/utilities.cpp.o.d -o CMakeFiles/tgui.dir/utilities.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/utilities.cpp                                Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [3/38] Building CXX object CMakeFiles/tgui.dir/image.cpp.o        FAILED: CMakeFiles/tgui.dir/image.cpp.o                           /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -Dtgui_EXPORTS -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/lz4 -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -ffast-math -Os -funroll-loops -fno-strict-aliasing -fno-math-errno -Wall -fno-rtti -finline-functions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -w -O3 -MD -MT CMakeFiles/tgui.dir/image.cpp.o -MF CMakeFiles/tgui.dir/image.cpp.o.d -o CMakeFiles/tgui.dir/image.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/image.cpp                                                Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [4/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiekeypath.cpp.o                                            FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiekeypath.cpp.o                                                               /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiekeypath.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiekeypath.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiekeypath.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottiekeypath.cpp                                                               Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [5/38] Building CXX object CMakeFiles/tgui.dir/lottie.cpp.o       FAILED: CMakeFiles/tgui.dir/lottie.cpp.o                          /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -Dtgui_EXPORTS -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/lz4 -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -ffast-math -Os -funroll-loops -fno-strict-aliasing -fno-math-errno -Wall -fno-rtti -finline-functions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -w -O3 -MD -MT CMakeFiles/tgui.dir/lottie.cpp.o -MF CMakeFiles/tgui.dir/lottie.cpp.o.d -o CMakeFiles/tgui.dir/lottie.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/lottie.cpp                                            Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [6/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiemodel.cpp.o                                              FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiemodel.cpp.o                                                                 /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiemodel.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiemodel.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottiemodel.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottiemodel.cpp     /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottiemodel.cpp:211:73: warning: '&&' within '||' [-Wlogical-op-parentheses]                                                     if (opacityArraySize % 2 != 0 || colorPoints > opacityArraySize / 2 && opacityArraySize < 4) {                                                                    ~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~                                     /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottiemodel.cpp:211:73: note: place parentheses around the '&&' expression to silence this warning                               if (opacityArraySize % 2 != 0 || colorPoints > opacityArraySize / 2 && opacityArraySize < 4) {                                                                                                          ^                                                                                                (                                                         )                                    1 warning generated.                                              Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [7/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieloader.cpp.o                                             FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieloader.cpp.o                                                                /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieloader.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieloader.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieloader.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottieloader.cpp                                                                   Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [8/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieanimation.cpp.o                                          FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieanimation.cpp.o                                                             /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieanimation.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieanimation.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieanimation.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottieanimation.cpp                                                       Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [9/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieitem.cpp.o                                               FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieitem.cpp.o                                                                  /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieitem.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieitem.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieitem.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottieitem.cpp         Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               [10/38] Building CXX object CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieparser.cpp.o                                            FAILED: CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieparser.cpp.o                                                                /data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ --target=armv7-none-linux-androideabi23 --gcc-toolchain=/data/data/com.termux/files/home/android-ndk-r23/toolchains/llvm/prebuilt/linux-aarch64 --sysroot=/data/data/com.termux/files/home/ndk-r21e-sysroot/sysroot -DHAVE_PTHREAD -DNDEBUG -DUSE_ARM_NEON -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/. -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/inc -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/pixman -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/freetype -I/storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/vector/stb -std=c++14 -DANDROID -g -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -Wall -fno-rtti -finline-functions -ffast-math -Os -fno-unwind-tables -fno-asynchronous-unwind-tables -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -fvisibility=hidden -fno-integrated-as -MD -MT CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieparser.cpp.o -MF CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieparser.cpp.o.d -o CMakeFiles/rlottie.dir/rlottie/src/lottie/lottieparser.cpp.o -c /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottieparser.cpp                                                                   /storage/emulated/0/AppProjects/TGUi/app/src/main/cpp/rlottie/src/lottie/lottieparser.cpp:185:60: warning: field 'colorMap' will be initialized after field 'mFitzModifier' [-Wreorder-ctor]                  : LookaheadParserHandler(str), mDirPath(dir_path), colorMap(colorReplacement), mFitzModifier(fitzModifier)                                                                             ^      1 warning generated.                                              Assembler messages:                                               Error: unrecognized option -mfpu=neon                             clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)                                               ninja: build stopped: subcommand failed.

**Comment by RohitVermaOP** [comment]
I want to compile telegram rlottie,

armv8a, x86, x86_64 compiled but armv7a not

**Comment by Lzhiyong** [comment]
I think the `-mfpu=neon` flag is not needed

this is my build.sh for armv7a
```bash
NDK_TOOLCHAIN=$HOME/opt/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64

cmake -G 'Ninja' \
    -DCMAKE_C_COMPILER=$NDK_TOOLCHAIN/bin/armv7a-linux-androideabi23-clang \
    -DCMAKE_CXX_COMPILER=$NDK_TOOLCHAIN/bin/armv7a-linux-androideabi23-clang++ \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=True \
    -DCMAKE_SYSROOT=$NDK_TOOLCHAIN/sysroot \
    -DCMAKE_BUILD_TYPE=Release \
    ..

```
![IMG_20220226_172101](https://user-images.githubusercontent.com/36750502/155837704-aa57e16f-0989-441d-98b5-90566ff52f7a.jpg)

**Comment by RohitVermaOP** [comment]
I'm compiling it on gradle with ndk + cmake

**Comment by Lzhiyong** [comment]
Can you give me the github link of this project?  I can try to compile, I don't think the problem comes from rlottie.

**Comment by RohitVermaOP** [comment]
My project

https://github.com/RohitVermaOP/TGUi

**Comment by RohitVermaOP** [comment]
Bro. Help me to build telegram rlottie using gradle on termux

**Comment by Lzhiyong** [comment]
The current workaround is to disable arm neon assembly.

**Comment by RohitVermaOP** [comment]
> 

![Screenshot_2022-03-02-22-49-53-04_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/156417847-7cb7afcb-9de8-413e-96b7-1fd919bb2c8f.jpg)

**Comment by RohitVermaOP** [comment]
![Uploading Screenshot_2022-03-02-23-20-15-36_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by RohitVermaOP** [comment]
![Screenshot_2022-03-02-23-20-15-36_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56387351/156419550-90c8d052-493d-45a5-88b4-e054040a5012.jpg)

**Comment by RohitVermaOP** [comment]
I think problem is not in ndk

**Comment by RohitVermaOP** [comment]
When i compile it with same ndk version on jitpak then is same happened,

When i changed ndk version 23.1.7779620 to 21.4.7075529 then it successfully compiled with jitpack

**Comment by RohitVermaOP** [comment]
[Here is project](https://github.com/RohitVermaOP/RLottie-Android)

How can I download ndk version 21.4.7075529 for Android?

**Comment by Lzhiyong** [comment]
![IMG_20220306_201218_1](https://user-images.githubusercontent.com/36750502/156922791-a85e762a-b1e4-40b8-b72d-a35b29721c8d.jpg)

same error for armv7a using termux's clang.
you can go to the termux community for discussion.
I really don't know how to fix it.

**Comment by RohitVermaOP** [comment]
> When i compile it with same ndk version (23.1.7779620) on jitpack then is same happened,
> 
> When i changed ndk version 23.1.7779620 to 21.4.7075529 then it successfully compiled with jitpack

**Comment by Lzhiyong** [comment]
> > When i changed ndk version 23.1.7779620 to 21.4.7075529 then it successfully compiled with jitpack

Using linux x86_64 to cross-compile arm works fine, but I haven't found the specific reason for cross-compiling arm on aarch64.

**Comment by RohitVermaOP** [comment]
Ok, thank you!
I will try it later
