### ISSUE TITLE
Ndk doesn't work

### ISSUE THREAD

**Issue by mjuned47** [Lzhiyong/termux-ndk#88]
Downloaded ndk r23 latest
![Screenshot_2022-03-01-22-39-05-814_com termux](https://user-images.githubusercontent.com/68558066/156215734-64c4cbd7-0372-4b67-8661-b2d156ddfb41.jpg)
Cannot link executable.. do i need to set ld_library_path or something?

Android version : 7
Device : Redmi Note 4

**Comment by Lzhiyong** [comment]
> Cannot link executable.. do i need to set ld_library_path or something?
> 
> Android version : 7 Device : Redmi Note 4

Requires Android 9 or above.

**Comment by mjuned47** [comment]
You should write it to Readme
