### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by linfei913** [Lzhiyong/termux-ndk#89]
I don't know how to solve this problem.

![Screenshot_2022-03-13-13-49-27-199_com termux](https://user-images.githubusercontent.com/88719743/158047032-bda5c6bf-755a-4008-ab07-ad9170f58ff2.jpg)

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @b0570e3

**Comment by Lzhiyong** [comment]
try using the `build-tools-31.0.0` provided by me

modity the build.gradle `buildToolsVersion='31.0.0'`

**Comment by linfei913** [comment]
However, 31 is set, display 31 is damaged, and it is still the same after deleting and rebuilding.



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 23:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Lzhiyong/termux-ndk] A question. (Issue #89)




 
try using the build-tools-31.0.0 provided by me
 
modity the build.gradle buildToolsVersion='31.0.0'
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
