### ISSUE TITLE
openjdk 11

### ISSUE THREAD

**Issue by hnmn** [Lzhiyong/termux-ndk#9]
how did you compile openjdk 11?

**Comment by Lzhiyong** [comment]
> how did you compile openjdk 11?

I am trying to use termux to compile openjdk, if successful, the build script will be released

**Comment by hnmn** [comment]
hey @Lzhiyong  can we build google's standalone gcc toolchain for termux. just like you compile llvm toolchain.

**Comment by Lzhiyong** [comment]
@hnmn ndk-r17 has gcc toolchain or you can try [gcc_termux](https://github.com/its-pointless/gcc_termux)

**Comment by nikey02** [comment]
Yes termux has a gcc but it's latest .I need gcc 4.9 for kernel building .

**Comment by hnmn** [comment]
termux has gcc but it's 10.2 . i need gcc 4.9 for compiling kernel.

**Comment by Lzhiyong** [comment]
Download ndk-r17 and export gcc-4.9 toolchain via make-standalone-toolchain.sh

**Comment by hnmn** [comment]
i don't get it i am little bit confused 
are you download ndk-r17 source or your released version .
can you elaborate please.

**Comment by Lzhiyong** [comment]
download [ndk-r17](https://github.com/Lzhiyong/termux-ndk/releases/tag/android-ndk-r17c)

![Screenshot_2020-10-17-20-35-12-024_org mozilla firefox](https://user-images.githubusercontent.com/36750502/96337295-ab5da500-10b8-11eb-9ece-4964b6ca0f92.jpg)

**Comment by hnmn** [comment]
ohh thanks i get it. file is in
`builds/tools/make-standalone-toolchain` right?

**Comment by Lzhiyong** [comment]
> ohh thanks i get it. file is in
> `builds/tools/make-standalone-toolchain.sh` right?

um yes

**Comment by hnmn** [comment]
so what are export options `aarch64-linux-android-4.9` or just `gcc-4.9`.

**Comment by Lzhiyong** [comment]
> so what are export options `aarch64-linux-android-4.9` or just `gcc-4.9`.
> also do i specific sysroot or something or not.
> i just don't want mess up.

aarch64-linux-android-4.9 
you need to specific sysroot and -pie -fPIE flags for executable binary file

**Comment by hnmn** [comment]
Thank you very much @Lzhiyong  finally i get toolchain

**Comment by hnmn** [comment]
> you need to specific sysroot and -pie -fPIE flags for executable binary file

sysroot from ndk path ?
actually i just type  `./make-standalone-toolchain.sh --arch=arm64 --platform=android-26`
and toolchain build successfully , is that right or i need something else 🤔

**Comment by Lzhiyong** [comment]
> > you need to specific sysroot and -pie -fPIE flags for executable binary file
> 
> sysroot from ndk path ?
> actually i just type `./make-standalone-toolchain.sh --arch=arm64 --platform=android-26`
> and toolchain build successfully , is that right or i need something else 🤔

for example aarch64-linux-android-gcc --sysroot=/path/to/sysroot -pie -fPIE -o test test.c

**Comment by hnmn** [comment]
again thanks @Lzhiyong i searched different places finally i got it 
thanks to you.
i need to test for compiling kernel 

```bash
┌u0_a81@localhost ~
└> /data/data/com.termux/files/home/toolchain/aarch64-linux-android/bin/aarch64-linux-android-gcc --sysroot=/data/data/com.termux/files/home/toolchain/aarch64-linux-android/sysroot/ -pie -FPIE hello.c -o hello
┌u0_a81@localhost ~
└> ./hello
hello
```
🎉🎉

**Comment by hnmn** [comment]
if you have any reference please share.
>/data/data/com.termux/files/home/toolchain/aarch64-linux-android/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find crtbegin_dynamic.o: No such file or directory                                                             /data/data/com.termux/files/home/toolchain/aarch64-linux-android/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lc                                    /data/data/com.termux/files/home/toolchain/aarch64-linux-android/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -ldl                                   /data/data/com.termux/files/home/toolchain/aarch64-linux-android/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find crtend_android.o: No such file or directory                                                               collect2: error: ld returned 1 exit status                         make[2]: *** [scripts/Makefile.host:100: scripts/kconfig/conf] Error 1
>
