### ISSUE TITLE
关于Android Studio

### ISSUE THREAD

**Issue by TapetalArray** [Lzhiyong/termux-ndk#90]
嗨，我在termux proot中安装了Ubuntu 21.10 aarch64，并且安装了Android Studio和SDK等一些工具，只不过SDK是x86_64的，通过 [Box64](https://github.com/ptitSeb/box64) 等一些用户空间模拟工具和修补脚本可以让platform-tools和build-tools以及gradle在arm64上工作，现在Android Studio可以构建不使用NDK的普通项目，但是我想让Android Studio构建NDK项目，我是否可以使用这个项目来实现这一点？Android Studio应该没有限制ndk的路径，将这个NDK放到termux里或者直接放在proot中，但是放在termux里可以让他构建的更快。我还没有做过任何测试，很高兴看到这个项目，它似乎省去了不少麻烦。

**Comment by Lzhiyong** [comment]
这些你可自行尝试，如果是在Box64下运行aarch64的Ndk肯定是不行的，Box64应该是可以直接运行官方的Ndk.
