### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rhamadhany** [Lzhiyong/termux-ndk#91]
Hi can you build an older ndk like version 19c. Because my source error when compiling with the newer version, I've tried 2 versions of yours. And the result is the same, But that's not the case in version 19c. I'm using v19c using proot but it feels really slow

**Comment by Lzhiyong** [comment]
Hmm, this is a bit of a hassle, I'm not considering offering an older version.

**Comment by Xinul-Hacker** [comment]
Hello
Do you happen to have an ndk compatible with legacy termux?
I'm trying to build with Android 5.
I
Thanks.

**Comment by rhamadhany** [comment]
> Hmm, this is a bit of a hassle, I'm not considering offering an older version.

how much space is needed to compile ndk-build? I don't have a pc. But maybe on my phone there is still about 20G+ space left

**Comment by Lzhiyong** [comment]
> 

about 30G+

**Comment by Lzhiyong** [comment]
> how much space is needed to compile ndk-build? I don't have a pc. But maybe on my phone there is still about 20G+ space left

about 30G+

**Comment by rhamadhany** [comment]
> > how much space is needed to compile ndk-build? I don't have a pc. But maybe on my phone there is still about 20G+ space left
> 
> about 30G+

okay. I'll think about it.. thanks for responding

**Comment by Xinul-Hacker** [comment]
Hopefully you change your mind. I'm in the same position.
Really want to use it on legacy Android. Maybe I could make a donation for
your time...

**Comment by Lzhiyong** [comment]
> Hello Do you happen to have an ndk compatible with legacy termux? I'm trying to build with Android 5. I Thanks.

Sorry, I provided a ndk-r17c version before, but it has been removed by me, I don't know if anyone has saved it, you can try to search on github.

**Comment by Xinul-Hacker** [comment]
https://github.com/kaozaza2/termux-jdk-11/releases/download/11.0.1/openjdk-jdk_11.0.1_aarch64.deb

Not sure if it's compatible with termux legacy, but this is what I found so
far.

**Comment by Xinul-Hacker** [comment]
Been searching on GitHub but I will continue. Hopefully someone still has
it.

 Wish they would have put it in the legacy archive.

https://archive.org/details/termux-repositories-legacy

Thanks for your help.

Best regards,

Excal
