### ISSUE TITLE
Please i need the previous r17c version

### ISSUE THREAD

**Issue by David770725** [Lzhiyong/termux-ndk#92]
I really need r17c version which is not available anymore in the released, it's the only tool that can build my program stable

**Comment by Xinul-Hacker** [comment]
I've been searching for days for someone who has it. No luck yet. ☹️

**Comment by billflx** [comment]
I have the c++ program which i build with ndk r17c back then, it's just normal, then i compile with the latest version of ndk it's just forced close, I'm hoping they still have r17c, i do really need help about this.

**Comment by Xinul-Hacker** [comment]
https://web.archive.org/web/20201031000850/https://github.com/Lzhiyong/termux-ndk/releases/download/android-ndk-r17c/android-ndk-r17c.tar.xz

**Comment by billflx** [comment]
> https://web.archive.org/web/20201031000850/https://github.com/Lzhiyong/termux-ndk/releases/download/android-ndk-r17c/android-ndk-r17c.tar.xz

Thank you so much!!

**Comment by Xinul-Hacker** [comment]
No problem.

It wasn't easy to find.
