### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by yutong-yt** [Lzhiyong/termux-ndk#97]
![Screenshot_2022-04-06-18-19-15-879_com termux](https://user-images.githubusercontent.com/84581911/161953836-89edf6c8-f01a-49ab-b712-08820ca18c18.jpg)
![Screenshot_2022-04-06-18-17-54-089_com termux](https://user-images.githubusercontent.com/84581911/161953847-28be5a0b-abf5-4bed-ac0e-cae28ae7b0d9.jpg)
无法编译

**Comment by Lzhiyong** [comment]
错误提示是找不到`libyt.so`，这个库是预编译好的，还是由源码编译生成的？我不知道你的`CMakeList.txt`是否写正确了.
另外如果你使用Termux的cmake进行编译，是需要进行打补丁的，查看 issue #76

**Comment by yutong-yt** [comment]
布丁不会用，有没有更详细的教程？项目在Android9上打包正常，在这个Android12上不正常


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 晚上7:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 无法使用 (Issue #97)




 
错误提示是找不到libyt.so，这个库是预编译好的，还是由源码编译生成的？我不知道你的CMakeList.txt是否写正确了.
 另外如果你使用Termux的cmake进行编译，是需要进行打补丁的，查看 issue #76
 
&mdash;

**Comment by Lzhiyong** [comment]
我自己用的是Android10，12的问题我也无法解决，另外错误输出的信息太少，无法确定到底是由什么引起这个问题！

**Comment by yutong-yt** [comment]
不用cmake可以解决这个问题吗？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 晚上8:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 无法使用 (Issue #97)




 
我自己用的是Android10，12的问题我也无法解决，另外错误输出的信息太少，无法确定到底是由什么引起这个问题！
 
&mdash;

**Comment by Lzhiyong** [comment]
> 不用cmake可以解决这个问题吗？
可以尝试改成ndk-build，看是否可以正常编译.

**Comment by yutong-yt** [comment]
cmake不是有官方arm64版本的吗？我可以替换吗？如何替换？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 晚上8:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/termux-ndk] 无法使用 (Issue #97)




  
不用cmake可以解决这个问题吗？
 可以尝试改成ndk-build，看是否可以正常编译.

**Comment by Lzhiyong** [comment]
参考 [pactches/cmake](https://github.com/Lzhiyong/termux-ndk/tree/master/patches/cmake) 找到这几个文件，进行手工修改.
